/**
 * Adaptable content rules — WCAG 1.3.x Info and Relationships
 */
import { AccessibilityRule } from '../types.js';

export const adaptableRules: AccessibilityRule[] = [
  {
    id: 'info-relationships-headings',
    category: 'adaptable',
    title: 'Heading hierarchy must be logical',
    description: 'Headings (h1-h6) must follow a logical nested order without skipping levels.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure headings follow a sequential order (h1 → h2 → h3). Do not skip levels.',
    selectorHints: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
    analysisMode: 'static',
    checkFunction: 'Extract all heading elements in DOM order. Verify no level is skipped (e.g., h1 followed by h3). Allow multiple h1s but flag if questionable.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'info-relationships-lists',
    category: 'adaptable',
    title: 'Lists must use proper list markup',
    description: 'Content that functions as a list must use <ul>, <ol>, or <dl> elements.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'minor',
    remediation: 'Use semantic list elements (<ul>, <ol>, <dl>) instead of styled divs or paragraphs.',
    selectorHints: ['ul', 'ol', 'dl', 'li'],
    analysisMode: 'static',
    checkFunction: 'Find <li> elements not inside <ul> or <ol>. Find patterns of repeated similar elements that could be lists but lack list markup.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'info-relationships-tables',
    category: 'adaptable',
    title: 'Data tables must have proper header markup',
    description: 'Data tables must use <th>, scope, or headers attributes to identify header cells.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'serious',
    remediation: 'Add <th> elements for header cells with appropriate scope attributes. Use headers/id for complex tables.',
    selectorHints: ['table', 'th', 'td[headers]'],
    analysisMode: 'static',
    checkFunction: 'Find <table> elements. Verify presence of <th> cells. Check scope attributes. For complex tables, verify headers/id associations.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'info-relationships-table-caption',
    category: 'adaptable',
    title: 'Data tables should have a caption or accessible name',
    description: 'Tables should have a <caption> or be labeled with aria-label/aria-labelledby.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'minor',
    remediation: 'Add a <caption> element or aria-label/aria-labelledby to the table.',
    selectorHints: ['table', 'caption'],
    analysisMode: 'static',
    checkFunction: 'Find <table> elements (excluding layout tables with role="presentation"). Check for <caption>, aria-label, or aria-labelledby.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'info-relationships-layout-tables',
    category: 'adaptable',
    title: 'Layout tables must not use structural markup',
    description: 'Tables used for layout must have role="presentation" and must not use <th>, <caption>, or summary.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'minor',
    remediation: 'Add role="presentation" to layout tables and remove any <th>, <caption>, or summary attributes.',
    selectorHints: ['table[role="presentation"]', 'table[role="none"]'],
    analysisMode: 'static',
    checkFunction: 'Find tables with role="presentation" or role="none". Verify they have no <th>, <caption>, or summary attributes.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'info-relationships-fieldset',
    category: 'adaptable',
    title: 'Related form controls must be grouped',
    description: 'Groups of related form controls (radio buttons, checkboxes) must use <fieldset>/<legend> or role="group".',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'serious',
    remediation: 'Wrap related controls in <fieldset> with <legend>, or use role="group" with aria-labelledby.',
    selectorHints: ['fieldset', 'legend', 'input[type="radio"]', 'input[type="checkbox"]'],
    analysisMode: 'static',
    checkFunction: 'Find groups of radio buttons or checkboxes sharing the same name. Verify they are inside a <fieldset>/<legend> or element with role="group" and accessible name.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'info-relationships-landmarks',
    category: 'adaptable',
    title: 'Page must use landmark regions',
    description: 'Page content must be organized using landmark regions (main, nav, header, footer, etc.).',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'minor',
    remediation: 'Use semantic HTML5 landmarks: <main>, <nav>, <header>, <footer>, <aside>, or equivalent ARIA roles.',
    selectorHints: ['main', 'nav', 'header', 'footer', 'aside', '[role="main"]', '[role="navigation"]'],
    analysisMode: 'static',
    checkFunction: 'Check page has at least one <main> or role="main". Verify all visible content is within a landmark region.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'meaningful-sequence',
    category: 'adaptable',
    title: 'Reading order must be meaningful',
    description: 'The DOM order must match the visual reading order so assistive technology reads content logically.',
    wcagReferences: [{ criterion: '1.3.2', name: 'Meaningful Sequence', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure the DOM order matches the visual presentation order. Avoid CSS that reorders content significantly.',
    selectorHints: ['[style*="order"]', '[style*="flex"]', '[style*="grid"]'],
    analysisMode: 'browser',
    checkFunction: 'Compare visual rendering order (via getBoundingClientRect) with DOM order. Flag significant discrepancies caused by CSS flex/grid order or absolute positioning.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'sensory-characteristics',
    category: 'adaptable',
    title: 'Instructions must not rely solely on sensory characteristics',
    description: 'Instructions must not depend only on shape, color, size, position, or sound.',
    wcagReferences: [{ criterion: '1.3.3', name: 'Sensory Characteristics', level: 'A' }],
    severity: 'minor',
    remediation: 'Supplement sensory cues with text labels. For example, "Click the round green button labeled Submit".',
    selectorHints: ['*'],
    analysisMode: 'manual',
    checkFunction: 'Scan text content for sensory-only instructions (e.g., "click the red button", "see the left panel"). Flag for manual review.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'orientation',
    category: 'adaptable',
    title: 'Content must not restrict display orientation',
    description: 'Content must not lock display to portrait or landscape unless essential.',
    wcagReferences: [{ criterion: '1.3.4', name: 'Orientation', level: 'AA' }],
    severity: 'serious',
    remediation: 'Remove CSS or JS that locks orientation. Use responsive design that works in both orientations.',
    selectorHints: ['meta[name="viewport"]'],
    analysisMode: 'browser',
    checkFunction: 'Check for CSS @media queries that hide content in one orientation. Check for JS orientation lock APIs. Test page renders in both portrait and landscape.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'identify-input-purpose',
    category: 'adaptable',
    title: 'Input fields must identify their purpose',
    description: 'Input fields collecting user information must have autocomplete attributes matching their purpose.',
    wcagReferences: [{ criterion: '1.3.5', name: 'Identify Input Purpose', level: 'AA' }],
    severity: 'minor',
    remediation: 'Add appropriate autocomplete attributes (e.g., autocomplete="name", autocomplete="email").',
    selectorHints: ['input[type="text"]', 'input[type="email"]', 'input[type="tel"]', 'select'],
    analysisMode: 'static',
    checkFunction: 'Find input fields that collect personal data (name, email, phone, address). Verify they have valid autocomplete attribute values from the HTML spec.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21'],
  },
  {
    id: 'identify-purpose',
    category: 'adaptable',
    title: 'UI component purpose should be programmatically determinable',
    description: 'The purpose of UI components, icons, and regions should be determinable from their semantics.',
    wcagReferences: [{ criterion: '1.3.6', name: 'Identify Purpose', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Use semantic HTML elements and ARIA landmarks. Add microdata or RDFa for machine-readable purpose.',
    selectorHints: ['[role]', 'nav', 'main', 'aside'],
    analysisMode: 'static',
    checkFunction: 'Check that interactive elements use correct semantic elements or ARIA roles. Verify icons have accessible labels. Check regions are properly identified.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'aaa'],
  },
];
