/**
 * ARIA-specific rules — valid roles, states, properties, labeling patterns.
 * Cross-cutting rules that enforce correct ARIA usage per WAI-ARIA 1.2.
 */
import { AccessibilityRule } from '../types.js';

export const ariaRules: AccessibilityRule[] = [
  {
    id: 'aria-valid-roles',
    category: 'aria',
    title: 'ARIA roles must be valid',
    description: 'All role attribute values must be valid WAI-ARIA 1.2 roles.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'critical',
    remediation: 'Use only valid ARIA roles from the WAI-ARIA 1.2 specification. Remove misspelled or invented roles.',
    selectorHints: ['[role]'],
    analysisMode: 'static',
    checkFunction: 'Extract all role attribute values. Validate against the complete WAI-ARIA 1.2 role taxonomy. Flag invalid, deprecated, or abstract roles.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-valid-attributes',
    category: 'aria',
    title: 'ARIA attributes must be valid',
    description: 'All aria-* attributes must be valid WAI-ARIA 1.2 attributes with valid values.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'critical',
    remediation: 'Use only valid ARIA attributes. Ensure values match expected types (boolean, ID reference, token).',
    selectorHints: ['[aria-*]'],
    analysisMode: 'static',
    checkFunction: 'Find all aria-* attributes. Validate attribute names against WAI-ARIA spec. Validate values: booleans (true/false), ID refs (target exists), tokens (from allowed list).',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-required-attributes',
    category: 'aria',
    title: 'ARIA roles must have required attributes',
    description: 'Elements with ARIA roles must include all required ARIA attributes for that role.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'critical',
    remediation: 'Add missing required attributes. E.g., role="checkbox" requires aria-checked, role="slider" requires aria-valuenow.',
    selectorHints: ['[role]'],
    analysisMode: 'static',
    checkFunction: 'For each element with a role, look up required ARIA attributes for that role from the spec. Verify all required attributes are present.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-allowed-attributes',
    category: 'aria',
    title: 'ARIA attributes must be allowed on the element role',
    description: 'Elements must only use ARIA attributes that are permitted for their role.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'serious',
    remediation: 'Remove ARIA attributes not permitted on the element\'s role. Consult WAI-ARIA allowed attributes per role.',
    selectorHints: ['[role]', '[aria-*]'],
    analysisMode: 'static',
    checkFunction: 'For each element, determine its role (explicit or implicit). Check each aria-* attribute against the allowed attributes list for that role.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-hidden-no-focusable',
    category: 'aria',
    title: 'aria-hidden elements must not contain focusable content',
    description: 'Elements with aria-hidden="true" must not contain focusable descendants.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'critical',
    remediation: 'Remove focusable elements from aria-hidden containers, or remove aria-hidden. Add tabindex="-1" to trapped focusable elements.',
    selectorHints: ['[aria-hidden="true"]'],
    analysisMode: 'static',
    checkFunction: 'Find all elements with aria-hidden="true". Search descendants for focusable elements (a[href], button, input, select, textarea, [tabindex >= 0]). Flag any found.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-hidden-body',
    category: 'aria',
    title: 'aria-hidden must not be set on body',
    description: 'The <body> element must not have aria-hidden="true" as it hides the entire page from assistive tech.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'critical',
    remediation: 'Remove aria-hidden from the <body> element. Use it only on specific decorative or duplicate content.',
    selectorHints: ['body[aria-hidden]'],
    analysisMode: 'static',
    checkFunction: 'Check if <body> has aria-hidden="true". Flag immediately as critical.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-labelledby-valid-ref',
    category: 'aria',
    title: 'aria-labelledby must reference existing elements',
    description: 'All IDs referenced in aria-labelledby must exist in the document.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure all IDs in aria-labelledby exist on the page. Fix misspelled or stale ID references.',
    selectorHints: ['[aria-labelledby]'],
    analysisMode: 'static',
    checkFunction: 'Find all aria-labelledby attributes. Split value by spaces to get ID list. Verify each ID exists in the DOM.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-describedby-valid-ref',
    category: 'aria',
    title: 'aria-describedby must reference existing elements',
    description: 'All IDs referenced in aria-describedby must exist in the document.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure all IDs in aria-describedby exist on the page.',
    selectorHints: ['[aria-describedby]'],
    analysisMode: 'static',
    checkFunction: 'Find all aria-describedby attributes. Split by spaces. Verify each referenced ID exists in the DOM.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-required-parent',
    category: 'aria',
    title: 'ARIA child roles must be nested in required parent roles',
    description: 'Certain ARIA roles must be nested inside specific parent roles (e.g., listitem inside list).',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure ARIA roles are properly nested: tab in tablist, listitem in list, row in table/grid/treegrid, etc.',
    selectorHints: ['[role="listitem"]', '[role="tab"]', '[role="row"]', '[role="option"]', '[role="treeitem"]'],
    analysisMode: 'static',
    checkFunction: 'For roles requiring a specific parent (tab→tablist, listitem→list, option→listbox, row→table/grid), walk up the DOM and verify the required parent role exists.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-required-children',
    category: 'aria',
    title: 'ARIA parent roles must contain required child roles',
    description: 'Certain ARIA roles must contain specific child roles (e.g., list must contain listitem).',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure container roles have proper children: tablist contains tab, list contains listitem, grid contains row.',
    selectorHints: ['[role="list"]', '[role="tablist"]', '[role="grid"]', '[role="tree"]', '[role="menu"]'],
    analysisMode: 'static',
    checkFunction: 'For roles requiring specific children (tablist→tab, list→listitem, menu→menuitem), verify at least one required child role exists among descendants.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-dialog-name',
    category: 'aria',
    title: 'Dialogs must have an accessible name',
    description: 'Elements with role="dialog" or role="alertdialog" must have aria-label or aria-labelledby.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'serious',
    remediation: 'Add aria-label or aria-labelledby pointing to the dialog title element.',
    selectorHints: ['[role="dialog"]', '[role="alertdialog"]', 'dialog'],
    analysisMode: 'static',
    checkFunction: 'Find dialog elements (role="dialog", role="alertdialog", <dialog>). Verify they have aria-label, aria-labelledby, or <dialog> with accessible name.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-meter-progressbar',
    category: 'aria',
    title: 'Progress bars and meters must have accessible values',
    description: 'Elements with role="progressbar" or role="meter" must have aria-valuenow, aria-valuemin, aria-valuemax.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'minor',
    remediation: 'Add aria-valuenow, aria-valuemin, aria-valuemax, and aria-label to progress/meter elements.',
    selectorHints: ['[role="progressbar"]', '[role="meter"]', 'progress', 'meter'],
    analysisMode: 'static',
    checkFunction: 'Find progressbar/meter elements. Verify required value attributes exist. Check aria-valuenow is between min and max.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-tooltip',
    category: 'aria',
    title: 'Tooltips must be properly associated',
    description: 'Elements with role="tooltip" must be referenced by aria-describedby on the triggering element.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'minor',
    remediation: 'Link the trigger element to the tooltip via aria-describedby pointing to the tooltip ID.',
    selectorHints: ['[role="tooltip"]'],
    analysisMode: 'static',
    checkFunction: 'Find elements with role="tooltip". Verify they have an ID. Find elements with aria-describedby referencing that ID. Flag orphaned tooltips.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'aria-live-regions',
    category: 'aria',
    title: 'Live regions must use correct aria-live values',
    description: 'aria-live must use valid values: "polite", "assertive", or "off". Use "assertive" sparingly.',
    wcagReferences: [{ criterion: '4.1.3', name: 'Status Messages', level: 'AA' }],
    severity: 'minor',
    remediation: 'Use aria-live="polite" for status updates. Reserve aria-live="assertive" for urgent alerts only.',
    selectorHints: ['[aria-live]'],
    analysisMode: 'static',
    checkFunction: 'Find all aria-live attributes. Validate values are "polite", "assertive", or "off". Flag excessive use of "assertive".',
    automationLevel: 'full',
    tags: ['automated'],
  },
];
