/**
 * Compatible rules — WCAG 4.1.x Robust
 * Covers parsing, name/role/value, status messages.
 */
import { AccessibilityRule } from '../types.js';

export const compatibleRules: AccessibilityRule[] = [
  {
    id: 'parsing-valid-html',
    category: 'compatible',
    title: 'HTML must be well-formed',
    description: 'HTML must have no duplicate IDs, proper nesting, and valid attributes. (4.1.1 is obsolete in WCAG 2.2 but remains a best practice.)',
    wcagReferences: [{ criterion: '4.1.1', name: 'Parsing', level: 'A' }],
    severity: 'minor',
    remediation: 'Fix HTML validation errors: remove duplicate IDs, close unclosed tags, fix improper nesting.',
    selectorHints: ['[id]'],
    analysisMode: 'static',
    checkFunction: 'Check for duplicate ID values across the page. Validate proper nesting of elements. Check for unclosed tags and invalid attributes.',
    automationLevel: 'full',
    tags: ['automated', 'deprecated-in-2.2'],
  },
  {
    id: 'duplicate-ids',
    category: 'compatible',
    title: 'ID attributes must be unique',
    description: 'Every id attribute value must be unique within the page to prevent assistive technology confusion.',
    wcagReferences: [{ criterion: '4.1.1', name: 'Parsing', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure all id values are unique. Generate unique IDs for dynamically created elements.',
    selectorHints: ['[id]'],
    analysisMode: 'static',
    checkFunction: 'Collect all id attribute values. Find duplicates. Flag each duplicate with the elements that share the same ID.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'name-role-value',
    category: 'compatible',
    title: 'UI components must have accessible name, role, and value',
    description: 'All UI components must expose their name, role, states, and values to assistive technology.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'critical',
    remediation: 'Use native HTML elements for their intended purpose. Add ARIA attributes when needed for custom components.',
    selectorHints: ['[role]', 'button', 'a', 'input', 'select', 'textarea', '[tabindex]'],
    analysisMode: 'browser',
    checkFunction: 'For all interactive elements, compute accessible name (must be non-empty), verify role is correct (native or ARIA), and check states/values are properly exposed.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'status-messages',
    category: 'compatible',
    title: 'Status messages must be programmatically determinable',
    description: 'Status messages (success, error, progress) must be conveyed to assistive technology via ARIA live regions.',
    wcagReferences: [{ criterion: '4.1.3', name: 'Status Messages', level: 'AA' }],
    severity: 'serious',
    remediation: 'Use role="status", role="alert", or aria-live regions for dynamic status messages.',
    selectorHints: ['[role="status"]', '[role="alert"]', '[aria-live]', '[class*="toast"]', '[class*="notification"]'],
    analysisMode: 'browser',
    checkFunction: 'Trigger form submissions and other actions that produce status messages. Verify status messages are inside aria-live regions or have role="status"/"alert".',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'custom-controls-role',
    category: 'compatible',
    title: 'Custom interactive controls must have appropriate ARIA roles',
    description: 'Custom-built interactive elements must use appropriate ARIA roles to convey their function.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'critical',
    remediation: 'Add ARIA roles (button, link, tab, dialog, etc.) to custom interactive elements. Prefer native HTML elements.',
    selectorHints: ['div[onclick]', 'span[onclick]', 'div[tabindex]', 'span[tabindex]'],
    analysisMode: 'static',
    checkFunction: 'Find non-semantic elements (div, span) with interactive attributes (onclick, tabindex, role). Verify they have appropriate ARIA roles and can be operated via keyboard.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'custom-controls-states',
    category: 'compatible',
    title: 'Custom controls must expose state changes',
    description: 'Custom interactive components must update ARIA states (aria-expanded, aria-selected, aria-checked) dynamically.',
    wcagReferences: [{ criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' }],
    severity: 'serious',
    remediation: 'Update ARIA state attributes (aria-expanded, aria-selected, aria-pressed, aria-checked) when control state changes.',
    selectorHints: ['[aria-expanded]', '[aria-selected]', '[aria-checked]', '[aria-pressed]'],
    analysisMode: 'browser',
    checkFunction: 'Find elements with ARIA state attributes. Interact with them (click, keyboard). Verify the ARIA state attribute value changes to reflect the new state.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
];
