/**
 * Distinguishable content rules — WCAG 1.4.x
 * Covers color contrast, resize, text spacing, reflow, non-text contrast.
 */
import { AccessibilityRule } from '../types.js';

export const distinguishableRules: AccessibilityRule[] = [
  {
    id: 'color-not-sole-indicator',
    category: 'distinguishable',
    title: 'Color must not be the sole means of conveying information',
    description: 'Information conveyed with color must also be available through text, patterns, or other visual cues.',
    wcagReferences: [{ criterion: '1.4.1', name: 'Use of Color', level: 'A' }],
    severity: 'serious',
    remediation: 'Add text labels, icons, patterns, or underlines alongside color cues. For links, add underline or other non-color indicator.',
    selectorHints: ['a', '[class*="error"]', '[class*="success"]', '[class*="warning"]'],
    analysisMode: 'browser',
    checkFunction: 'Check links inside text blocks — verify non-color distinction (underline, border, font-weight). Scan form fields for color-only error states.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'contrast-minimum',
    category: 'distinguishable',
    title: 'Text must meet minimum contrast ratio (4.5:1)',
    description: 'Normal text must have a contrast ratio of at least 4.5:1 against its background.',
    wcagReferences: [{ criterion: '1.4.3', name: 'Contrast (Minimum)', level: 'AA' }],
    severity: 'critical',
    remediation: 'Adjust foreground or background colors to achieve at least 4.5:1 contrast ratio.',
    selectorHints: ['*'],
    analysisMode: 'browser',
    checkFunction: 'For each text node, compute foreground color and effective background color (including layered backgrounds, gradients, images). Calculate luminance contrast ratio per WCAG formula. Flag ratios below 4.5:1 for normal text.',
    automationLevel: 'full',
    tags: ['automated', 'needs-browser'],
  },
  {
    id: 'contrast-large-text',
    category: 'distinguishable',
    title: 'Large text must meet 3:1 contrast ratio',
    description: 'Large text (18pt+ or 14pt+ bold) must have a contrast ratio of at least 3:1.',
    wcagReferences: [{ criterion: '1.4.3', name: 'Contrast (Minimum)', level: 'AA' }],
    severity: 'critical',
    remediation: 'Adjust colors to achieve at least 3:1 contrast for large text.',
    selectorHints: ['h1', 'h2', 'h3', '[style*="font-size"]'],
    analysisMode: 'browser',
    checkFunction: 'Identify large text (computed font-size >= 18pt or >= 14pt with bold). Calculate contrast ratio. Flag ratios below 3:1.',
    automationLevel: 'full',
    tags: ['automated', 'needs-browser'],
  },
  {
    id: 'contrast-enhanced',
    category: 'distinguishable',
    title: 'Text should meet enhanced contrast ratio (7:1)',
    description: 'Normal text should have a contrast ratio of at least 7:1 for enhanced accessibility.',
    wcagReferences: [{ criterion: '1.4.6', name: 'Contrast (Enhanced)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Adjust colors to achieve 7:1 contrast for normal text, 4.5:1 for large text.',
    selectorHints: ['*'],
    analysisMode: 'browser',
    checkFunction: 'Same as contrast-minimum but with 7:1 threshold for normal text and 4.5:1 for large text.',
    automationLevel: 'full',
    tags: ['automated', 'needs-browser', 'aaa'],
  },
  {
    id: 'resize-text-200',
    category: 'distinguishable',
    title: 'Text must be resizable to 200% without loss',
    description: 'Text must be resizable up to 200% without assistive technology and without loss of content or function.',
    wcagReferences: [{ criterion: '1.4.4', name: 'Resize Text', level: 'AA' }],
    severity: 'serious',
    remediation: 'Use relative units (em, rem, %) instead of px for font sizes. Test at 200% zoom.',
    selectorHints: ['[style*="font-size"]'],
    analysisMode: 'browser',
    checkFunction: 'Set browser zoom to 200%. Check for text overflow, clipping (overflow:hidden), overlapping elements, and horizontal scrolling. Verify all text remains readable.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'images-of-text',
    category: 'distinguishable',
    title: 'Images of text must not be used',
    description: 'Text should be presented as actual text, not as images of text, except for logos.',
    wcagReferences: [{ criterion: '1.4.5', name: 'Images of Text', level: 'AA' }],
    severity: 'minor',
    remediation: 'Replace images of text with styled HTML text. Exception: logos and brand names.',
    selectorHints: ['img'],
    analysisMode: 'browser',
    checkFunction: 'Use OCR or AI vision to detect text in images. Flag images containing readable text that could be rendered as HTML. Exclude logos (small images, in header/footer).',
    automationLevel: 'partial',
    tags: ['semi-automated', 'ai-assisted', 'needs-browser'],
  },
  {
    id: 'images-of-text-no-exception',
    category: 'distinguishable',
    title: 'Images of text should not be used (no exceptions)',
    description: 'Images of text should only be used for pure decoration or where presentation is essential.',
    wcagReferences: [{ criterion: '1.4.9', name: 'Images of Text (No Exception)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Replace all images of text with styled HTML text.',
    selectorHints: ['img'],
    analysisMode: 'browser',
    checkFunction: 'Same as images-of-text but with stricter requirements — only decorative images or essential presentations allowed.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'ai-assisted', 'aaa'],
  },
  {
    id: 'low-background-audio',
    category: 'distinguishable',
    title: 'Speech audio should have low background noise',
    description: 'Pre-recorded audio with speech should have background sounds at least 20dB lower.',
    wcagReferences: [{ criterion: '1.4.7', name: 'Low or No Background Audio', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Reduce background noise in audio content to at least 20dB below foreground speech.',
    selectorHints: ['audio', 'video'],
    analysisMode: 'manual',
    checkFunction: 'Flag audio/video elements for manual audio quality review.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'visual-presentation',
    category: 'distinguishable',
    title: 'Text blocks should have configurable visual presentation',
    description: 'Blocks of text should allow user control of colors, width (≤80 chars), line spacing, and alignment.',
    wcagReferences: [{ criterion: '1.4.8', name: 'Visual Presentation', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Ensure text blocks: max 80 chars wide, not fully justified, line spacing ≥1.5, paragraph spacing ≥2x line spacing, resizable to 200%.',
    selectorHints: ['p', 'div', '[style*="text-align: justify"]'],
    analysisMode: 'browser',
    checkFunction: 'Check text blocks for: full justification, line width > 80 characters, line-height < 1.5, paragraph spacing. Verify colors are not fixed in a way that prevents user override.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser', 'aaa'],
  },
  {
    id: 'reflow-320px',
    category: 'distinguishable',
    title: 'Content must reflow at 320px width',
    description: 'Content must reflow to a single column at 320 CSS px (equivalent to 400% zoom at 1280px) without horizontal scrolling.',
    wcagReferences: [{ criterion: '1.4.10', name: 'Reflow', level: 'AA' }],
    severity: 'serious',
    remediation: 'Use responsive CSS. Avoid fixed widths. Test at 320px viewport width.',
    selectorHints: ['[style*="width"]', '[style*="min-width"]'],
    analysisMode: 'browser',
    checkFunction: 'Set viewport to 320px width. Check for horizontal scrollbar. Detect content overflow (scrollWidth > clientWidth). Verify no two-dimensional scrolling except for data tables, maps, diagrams.',
    automationLevel: 'full',
    tags: ['automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'non-text-contrast',
    category: 'distinguishable',
    title: 'Non-text elements must have 3:1 contrast',
    description: 'UI components (borders, focus indicators) and meaningful graphics must have 3:1 contrast ratio.',
    wcagReferences: [{ criterion: '1.4.11', name: 'Non-text Contrast', level: 'AA' }],
    severity: 'serious',
    remediation: 'Ensure form field borders, icons, chart colors, and focus indicators have at least 3:1 contrast against adjacent colors.',
    selectorHints: ['input', 'select', 'button', 'svg', '[role="img"]'],
    analysisMode: 'browser',
    checkFunction: 'Identify UI component boundaries (input borders, button outlines, icon colors). Calculate contrast against adjacent background. Flag ratios below 3:1.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'text-spacing',
    category: 'distinguishable',
    title: 'Content must adapt to text spacing changes',
    description: 'No loss of content when: line-height 1.5x, paragraph spacing 2x, letter spacing 0.12em, word spacing 0.16em.',
    wcagReferences: [{ criterion: '1.4.12', name: 'Text Spacing', level: 'AA' }],
    severity: 'serious',
    remediation: 'Do not use fixed heights on text containers. Use relative units for spacing. Ensure overflow is visible.',
    selectorHints: ['[style*="height"]', '[style*="overflow: hidden"]', '[style*="line-height"]'],
    analysisMode: 'browser',
    checkFunction: 'Inject text spacing overrides via JS: line-height:1.5em, paragraph margin-bottom:2em, letter-spacing:0.12em, word-spacing:0.16em. Detect clipping or overlapping content.',
    automationLevel: 'full',
    tags: ['automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'content-hover-focus',
    category: 'distinguishable',
    title: 'Hover/focus content must be dismissible, hoverable, and persistent',
    description: 'Additional content appearing on hover/focus must be dismissible (Esc), hoverable, and persistent until dismissed.',
    wcagReferences: [{ criterion: '1.4.13', name: 'Content on Hover or Focus', level: 'AA' }],
    severity: 'minor',
    remediation: 'Ensure tooltips and popups: can be dismissed with Esc, remain while hovering over them, stay visible until user dismisses or trigger is removed.',
    selectorHints: ['[title]', '[data-tooltip]', ':hover', ':focus'],
    analysisMode: 'browser',
    checkFunction: 'Trigger hover/focus on elements with tooltips or popover content. Test: (1) Esc dismisses, (2) hovering over the popup keeps it open, (3) content persists until deliberate dismissal.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'needs-browser'],
  },
];
