/**
 * Forms accessibility rules — cross-cutting form patterns.
 * Labels, groups, errors, autocomplete, required fields.
 */
import { AccessibilityRule } from '../types.js';

export const formRules: AccessibilityRule[] = [
  {
    id: 'form-label-association',
    category: 'forms',
    title: 'Form inputs must have associated labels',
    description: 'Every form input must have a label associated via for/id, wrapping, aria-label, or aria-labelledby.',
    wcagReferences: [
      { criterion: '1.3.1', name: 'Info and Relationships', level: 'A' },
      { criterion: '3.3.2', name: 'Labels or Instructions', level: 'A' },
    ],
    severity: 'critical',
    remediation: 'Add <label for="inputId"> matching the input id, or wrap input in <label>, or use aria-label/aria-labelledby.',
    selectorHints: ['input:not([type="hidden"])', 'select', 'textarea'],
    analysisMode: 'static',
    checkFunction: 'Find all visible form inputs. For each, check: (1) <label> with matching for/id, (2) input wrapped in <label>, (3) aria-label, (4) aria-labelledby, (5) title. Flag if none found.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'form-label-visible',
    category: 'forms',
    title: 'Form labels must be visible',
    description: 'Form labels should be visible on screen, not hidden or replaced solely by placeholder text.',
    wcagReferences: [{ criterion: '3.3.2', name: 'Labels or Instructions', level: 'A' }],
    severity: 'serious',
    remediation: 'Use visible <label> elements. Placeholders supplement but do not replace labels.',
    selectorHints: ['input[placeholder]:not([aria-label])', 'label'],
    analysisMode: 'browser',
    checkFunction: 'Find inputs with placeholder but no visible label. Check if labels are visually hidden (display:none, visibility:hidden, clip, sr-only class without visible alternative).',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'form-required-indicator',
    category: 'forms',
    title: 'Required fields must be indicated',
    description: 'Required form fields must be clearly indicated both visually and programmatically.',
    wcagReferences: [
      { criterion: '3.3.2', name: 'Labels or Instructions', level: 'A' },
      { criterion: '1.3.1', name: 'Info and Relationships', level: 'A' },
    ],
    severity: 'serious',
    remediation: 'Use the required attribute or aria-required="true". Add visual indicator (asterisk with legend explanation).',
    selectorHints: ['[required]', '[aria-required]'],
    analysisMode: 'static',
    checkFunction: 'Find inputs with required or aria-required. Verify visual indication exists (asterisk, text). Find forms with mix of required/optional — ensure required fields are clearly distinguished.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'form-fieldset-legend',
    category: 'forms',
    title: 'Fieldsets must have legends',
    description: 'Every <fieldset> must have a <legend> as its first child to describe the group.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'serious',
    remediation: 'Add a <legend> element as the first child of each <fieldset>.',
    selectorHints: ['fieldset', 'legend'],
    analysisMode: 'static',
    checkFunction: 'Find all <fieldset> elements. Verify each has a <legend> child. Check <legend> is not empty.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'form-autocomplete',
    category: 'forms',
    title: 'Personal data inputs should have autocomplete',
    description: 'Inputs collecting personal information must use appropriate autocomplete attribute values.',
    wcagReferences: [{ criterion: '1.3.5', name: 'Identify Input Purpose', level: 'AA' }],
    severity: 'minor',
    remediation: 'Add autocomplete values: "name", "email", "tel", "address-line1", "postal-code", "cc-number", etc.',
    selectorHints: ['input[type="text"]', 'input[type="email"]', 'input[type="tel"]', 'input[name*="name"]', 'input[name*="email"]'],
    analysisMode: 'static',
    checkFunction: 'Identify inputs collecting personal data by type, name, and label. Verify appropriate autocomplete attribute is set with a valid value from the HTML spec list.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21'],
  },
  {
    id: 'form-error-association',
    category: 'forms',
    title: 'Error messages must be programmatically associated',
    description: 'Error messages for form fields must be associated via aria-describedby or aria-errormessage.',
    wcagReferences: [{ criterion: '3.3.1', name: 'Error Identification', level: 'A' }],
    severity: 'serious',
    remediation: 'Link error messages to their input via aria-describedby or aria-errormessage. Set aria-invalid="true" on the field.',
    selectorHints: ['[aria-invalid]', '[aria-describedby]', '[aria-errormessage]'],
    analysisMode: 'browser',
    checkFunction: 'Trigger validation errors. Find inputs with aria-invalid="true". Verify they have aria-describedby or aria-errormessage pointing to visible error text.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'form-submit-button',
    category: 'forms',
    title: 'Forms must have a submit mechanism',
    description: 'Every form should have a visible submit button or equivalent mechanism.',
    wcagReferences: [{ criterion: '3.2.2', name: 'On Input', level: 'A' }],
    severity: 'minor',
    remediation: 'Add a <button type="submit"> or <input type="submit"> to each form.',
    selectorHints: ['form', 'button[type="submit"]', 'input[type="submit"]'],
    analysisMode: 'static',
    checkFunction: 'Find all <form> elements. Check for a submit button (type="submit" or type="image") or a button element inside the form.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'form-no-paste-blocking',
    category: 'forms',
    title: 'Password fields must not block paste',
    description: 'Password and other input fields must not prevent pasting from clipboard (blocks password managers).',
    wcagReferences: [{ criterion: '3.3.8', name: 'Accessible Authentication (Minimum)', level: 'AA' }],
    severity: 'serious',
    remediation: 'Remove onpaste="return false" or JavaScript preventing clipboard paste on input fields.',
    selectorHints: ['input[type="password"]', '[onpaste]'],
    analysisMode: 'static',
    checkFunction: 'Find inputs with onpaste event handlers that return false or call preventDefault. Also check for JavaScript paste prevention on password fields.',
    automationLevel: 'full',
    tags: ['automated', 'new-in-2.2'],
  },
  {
    id: 'form-select-accessible',
    category: 'forms',
    title: 'Custom select/dropdown components must be accessible',
    description: 'Custom dropdown components must implement proper ARIA patterns (combobox or listbox).',
    wcagReferences: [
      { criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' },
      { criterion: '2.1.1', name: 'Keyboard', level: 'A' },
    ],
    severity: 'serious',
    remediation: 'Use native <select> or implement ARIA combobox/listbox pattern with keyboard navigation.',
    selectorHints: ['[role="combobox"]', '[role="listbox"]', '[class*="dropdown"]', '[class*="select"]'],
    analysisMode: 'browser',
    checkFunction: 'Find custom dropdown components (non-native selects). Check for proper ARIA roles (combobox, listbox), keyboard navigation (arrow keys, Enter, Esc), and accessible name.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'form-input-type',
    category: 'forms',
    title: 'Inputs should use appropriate type attributes',
    description: 'Form inputs should use the correct type (email, tel, url, number, date) for mobile keyboards and validation.',
    wcagReferences: [{ criterion: '1.3.5', name: 'Identify Input Purpose', level: 'AA' }],
    severity: 'minor',
    remediation: 'Use type="email" for email fields, type="tel" for phone, type="url" for URLs, etc.',
    selectorHints: ['input[type="text"]'],
    analysisMode: 'static',
    checkFunction: 'Find text inputs. Analyze label/name/placeholder to infer expected data type. Flag inputs that could use a more specific type (email, tel, url, number, date).',
    automationLevel: 'partial',
    tags: ['semi-automated', 'best-practice'],
  },
];
