/**
 * Image accessibility rules — WCAG 1.1.1 Non-text Content
 */
import { AccessibilityRule } from '../types.js';

export const imageRules: AccessibilityRule[] = [
  {
    id: 'img-alt-text',
    category: 'images',
    title: 'Images must have alt text',
    description: 'All <img> elements must have an alt attribute providing a text alternative.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'critical',
    remediation: 'Add a descriptive alt attribute to the <img> element. Use alt="" for decorative images.',
    selectorHints: ['img'],
    analysisMode: 'static',
    checkFunction: 'Query all <img> elements. Verify each has an alt attribute. Flag missing alt or alt with only whitespace.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'img-alt-quality',
    category: 'images',
    title: 'Alt text should be meaningful',
    description: 'Alt text should not be generic (e.g., "image", "photo", "picture") or a filename.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'serious',
    remediation: 'Replace generic alt text with a description of the image content and purpose.',
    selectorHints: ['img[alt]'],
    analysisMode: 'static',
    checkFunction: 'Check alt text against blocklist of generic words (image, photo, picture, graphic, icon, img_, DSC_, IMG_). Flag filenames with extensions.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'img-decorative-role',
    category: 'images',
    title: 'Decorative images must be hidden from assistive tech',
    description: 'Images that are purely decorative should have alt="" or role="presentation" or role="none".',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'minor',
    remediation: 'Set alt="" and optionally role="presentation" on decorative images.',
    selectorHints: ['img[role="presentation"]', 'img[role="none"]', 'img[alt=""]'],
    analysisMode: 'static',
    checkFunction: 'Find images with role="presentation" or role="none". Verify they also have alt="". Find images with empty alt — confirm no role conflict.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'img-svg-accessible',
    category: 'images',
    title: 'SVG images must have accessible names',
    description: 'Inline SVGs used as images must have a <title> element or aria-label/aria-labelledby.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'serious',
    remediation: 'Add a <title> as first child of <svg>, or use aria-label/aria-labelledby on the SVG element.',
    selectorHints: ['svg', 'svg[role="img"]'],
    analysisMode: 'static',
    checkFunction: 'Query all <svg> elements with role="img" or without role="presentation". Check for <title> child, aria-label, or aria-labelledby.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'img-input-alt',
    category: 'images',
    title: 'Image inputs must have alt text',
    description: '<input type="image"> elements must have an alt attribute describing the button action.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'critical',
    remediation: 'Add an alt attribute to the <input type="image"> describing its function (e.g., alt="Submit").',
    selectorHints: ['input[type="image"]'],
    analysisMode: 'static',
    checkFunction: 'Query all input[type="image"]. Verify each has a non-empty alt attribute.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'img-area-alt',
    category: 'images',
    title: 'Image map areas must have alt text',
    description: 'Each <area> element in an image map must have alt text describing the link destination.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'critical',
    remediation: 'Add alt text to each <area> element in the image map.',
    selectorHints: ['area', 'map'],
    analysisMode: 'static',
    checkFunction: 'Query all <area> elements. Verify each has a non-empty alt attribute.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'img-figure-caption',
    category: 'images',
    title: 'Complex images should use figure/figcaption',
    description: 'Complex images (charts, diagrams) should be wrapped in <figure> with <figcaption> for long description.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'minor',
    remediation: 'Wrap complex images in <figure> and provide a <figcaption> with detailed description.',
    selectorHints: ['figure', 'figcaption', 'img'],
    analysisMode: 'static',
    checkFunction: 'Identify images with long alt text (>125 chars) that are not inside a <figure>. Flag as candidates for figure/figcaption pattern.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'best-practice'],
  },
  {
    id: 'img-canvas-fallback',
    category: 'images',
    title: 'Canvas elements must have text alternatives',
    description: '<canvas> elements must contain fallback content or have an accessible name via aria-label.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'serious',
    remediation: 'Add fallback content inside <canvas> tags or use aria-label/aria-labelledby.',
    selectorHints: ['canvas'],
    analysisMode: 'static',
    checkFunction: 'Query all <canvas> elements. Check for inner fallback text content, aria-label, or aria-labelledby.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'img-object-fallback',
    category: 'images',
    title: 'Object/embed elements must have text alternatives',
    description: '<object> and <embed> elements must provide accessible alternatives.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'serious',
    remediation: 'Provide text content inside <object> or use aria-label. For <embed>, provide adjacent text alternative.',
    selectorHints: ['object', 'embed'],
    analysisMode: 'static',
    checkFunction: 'Query <object> and <embed> elements. For <object>, check for inner text content or aria-label. For <embed>, check aria-label or adjacent descriptive element.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'img-css-background-alt',
    category: 'images',
    title: 'Meaningful CSS background images need text alternatives',
    description: 'CSS background images that convey information must have a text alternative in the DOM.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'serious',
    remediation: 'Add visible or SR-only text describing the background image content, or use an appropriate ARIA label.',
    selectorHints: ['[style*="background-image"]', '[style*="background:"]'],
    analysisMode: 'browser',
    checkFunction: 'Compute styles for all elements. Find elements with background-image that are not purely decorative. Check if the element or its children provide a text alternative.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
];
