/**
 * Input modalities rules — WCAG 2.5.x
 * Covers pointer gestures, motion, target size, dragging, label in name.
 */
import { AccessibilityRule } from '../types.js';

export const inputModalityRules: AccessibilityRule[] = [
  {
    id: 'pointer-gestures',
    category: 'input-modalities',
    title: 'Multipoint gestures must have single-pointer alternative',
    description: 'Functionality using multipoint or path-based gestures must have single-pointer alternatives.',
    wcagReferences: [{ criterion: '2.5.1', name: 'Pointer Gestures', level: 'A' }],
    severity: 'serious',
    remediation: 'Provide button or tap alternatives for pinch-to-zoom, swipe, or multi-finger gestures.',
    selectorHints: ['[ontouchstart]', '[ongesturestart]', 'canvas'],
    analysisMode: 'browser',
    checkFunction: 'Detect touch gesture event listeners (touchstart, gesturestart, pointermove). Check for single-pointer alternatives (buttons, taps) for the same functionality.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'pointer-cancellation',
    category: 'input-modalities',
    title: 'Down-event must not trigger functionality',
    description: 'Functionality must not trigger on the down-event (mousedown/touchstart). Use up-event or click, with ability to abort.',
    wcagReferences: [{ criterion: '2.5.2', name: 'Pointer Cancellation', level: 'A' }],
    severity: 'serious',
    remediation: 'Use click or mouseup/touchend events instead of mousedown/touchstart. Allow dragging away to cancel.',
    selectorHints: ['[onmousedown]', '[ontouchstart]'],
    analysisMode: 'static',
    checkFunction: 'Find elements with mousedown/touchstart handlers that trigger actions (not just visual feedback). Verify click or mouseup handlers exist as the actual trigger.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21'],
  },
  {
    id: 'label-in-name',
    category: 'input-modalities',
    title: 'Visible label must be part of accessible name',
    description: 'For UI components with visible text labels, the accessible name must contain the visible text.',
    wcagReferences: [{ criterion: '2.5.3', name: 'Label in Name', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure aria-label includes the visible text. Use aria-labelledby referencing the visible label. Do not override visible text with different aria-label.',
    selectorHints: ['[aria-label]', 'button', 'a', 'input', '[role="button"]'],
    analysisMode: 'browser',
    checkFunction: 'For elements with visible text and aria-label/aria-labelledby, verify the accessible name contains the visible text string. Use computeAccessibleName and compare.',
    automationLevel: 'full',
    tags: ['automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'motion-actuation',
    category: 'input-modalities',
    title: 'Motion-triggered actions must have UI alternative',
    description: 'Functionality triggered by device motion (shake, tilt) must have a UI alternative and be disableable.',
    wcagReferences: [{ criterion: '2.5.4', name: 'Motion Actuation', level: 'A' }],
    severity: 'serious',
    remediation: 'Provide a button or other UI control as an alternative to motion-based actions. Allow disabling motion activation.',
    selectorHints: ['[ondevicemotion]', '[ondeviceorientation]'],
    analysisMode: 'browser',
    checkFunction: 'Detect devicemotion and deviceorientation event listeners. Check for equivalent UI controls and a way to disable motion actuation.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'target-size-enhanced',
    category: 'input-modalities',
    title: 'Touch targets should be at least 44×44 CSS px',
    description: 'The size of interactive targets should be at least 44×44 CSS pixels for enhanced accessibility.',
    wcagReferences: [{ criterion: '2.5.5', name: 'Target Size (Enhanced)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Increase padding/size of interactive elements to at least 44×44 CSS pixels.',
    selectorHints: ['button', 'a', 'input', '[role="button"]', '[role="link"]', '[role="tab"]'],
    analysisMode: 'browser',
    checkFunction: 'Measure bounding box of all interactive elements via getBoundingClientRect. Flag elements with width or height < 44px. Exclude inline links within text.',
    automationLevel: 'full',
    tags: ['automated', 'wcag21', 'needs-browser', 'aaa'],
  },
  {
    id: 'dragging-movements',
    category: 'input-modalities',
    title: 'Dragging must have a single-pointer alternative',
    description: 'Functionality requiring dragging must have a non-dragging alternative (e.g., buttons, text input).',
    wcagReferences: [{ criterion: '2.5.7', name: 'Dragging Movements', level: 'AA' }],
    severity: 'serious',
    remediation: 'Provide click/tap alternatives for drag operations. For reordering, add up/down buttons.',
    selectorHints: ['[draggable="true"]', '[ondragstart]', '[class*="sortable"]', '[class*="draggable"]'],
    analysisMode: 'browser',
    checkFunction: 'Find elements with draggable attribute or drag event handlers. Check for alternative non-drag interactions (buttons, menus, text inputs) for the same functionality.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'needs-browser'],
  },
  {
    id: 'target-size-minimum',
    category: 'input-modalities',
    title: 'Touch targets must be at least 24×24 CSS px',
    description: 'Interactive targets must be at least 24×24 CSS pixels, with sufficient spacing from other targets.',
    wcagReferences: [{ criterion: '2.5.8', name: 'Target Size (Minimum)', level: 'AA' }],
    severity: 'serious',
    remediation: 'Increase target size to at least 24×24px. If smaller, ensure 24px of spacing to adjacent targets. Exceptions: inline text links, user-agent controlled, legally required sizes.',
    selectorHints: ['button', 'a', 'input', '[role="button"]', '[role="link"]'],
    analysisMode: 'browser',
    checkFunction: 'Measure all interactive element sizes via getBoundingClientRect. For elements < 24×24px, measure distance to nearest adjacent interactive element. Flag if target + spacing < 24px in any dimension.',
    automationLevel: 'full',
    tags: ['automated', 'new-in-2.2', 'needs-browser'],
  },
  {
    id: 'voice-access-labels',
    category: 'input-modalities',
    title: 'Interactive elements must have speakable labels for voice access',
    description: 'All interactive elements must have accessible names that can be spoken for voice control software.',
    wcagReferences: [
      { criterion: '2.5.3', name: 'Label in Name', level: 'A' },
      { criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' },
    ],
    severity: 'serious',
    remediation: 'Ensure all buttons, links, and controls have text-based accessible names pronounceable by voice software.',
    selectorHints: ['button', 'a', 'input', '[role="button"]', '[role="link"]'],
    analysisMode: 'browser',
    checkFunction: 'Compute accessible names of all interactive elements. Flag elements with no accessible name, icon-only names, or names that are not speakable text.',
    automationLevel: 'full',
    tags: ['automated', 'voice-access', 'needs-browser'],
  },
];
