/**
 * Input assistance rules — WCAG 3.3.x
 * Covers error identification, labels, suggestions, error prevention, authentication.
 */
import { AccessibilityRule } from '../types.js';

export const inputAssistanceRules: AccessibilityRule[] = [
  {
    id: 'error-identification',
    category: 'input-assistance',
    title: 'Input errors must be identified and described in text',
    description: 'When an input error is detected, the item in error must be identified and described to the user in text.',
    wcagReferences: [{ criterion: '3.3.1', name: 'Error Identification', level: 'A' }],
    severity: 'critical',
    remediation: 'Display text error messages near the field. Use aria-invalid="true" and aria-describedby linking to the error message.',
    selectorHints: ['[aria-invalid]', '[class*="error"]', '[class*="invalid"]'],
    analysisMode: 'browser',
    checkFunction: 'Submit forms with empty required fields. Check that error messages appear as text (not only color changes). Verify aria-invalid is set and error text is programmatically associated.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'labels-or-instructions',
    category: 'input-assistance',
    title: 'Form inputs must have labels or instructions',
    description: 'Labels or instructions must be provided when content requires user input.',
    wcagReferences: [{ criterion: '3.3.2', name: 'Labels or Instructions', level: 'A' }],
    severity: 'critical',
    remediation: 'Add <label> elements, aria-label, or aria-labelledby to all form inputs. Add instructions for complex inputs.',
    selectorHints: ['input', 'select', 'textarea', 'label'],
    analysisMode: 'static',
    checkFunction: 'Find all form inputs. Verify each has an associated <label> (for/id match), aria-label, aria-labelledby, or title attribute.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'error-suggestion',
    category: 'input-assistance',
    title: 'Error messages should suggest corrections',
    description: 'When input errors are detected and suggestions are available, they should be provided to the user.',
    wcagReferences: [{ criterion: '3.3.3', name: 'Error Suggestion', level: 'AA' }],
    severity: 'minor',
    remediation: 'Include specific correction suggestions in error messages (e.g., "Date must be in MM/DD/YYYY format").',
    selectorHints: ['[aria-invalid]', '[class*="error"]'],
    analysisMode: 'browser',
    checkFunction: 'Trigger form validation errors. Check that error messages contain constructive suggestions, not just "invalid input". Use AI to assess message quality.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'ai-assisted', 'needs-browser'],
  },
  {
    id: 'error-prevention-legal',
    category: 'input-assistance',
    title: 'Legal/financial submissions must be reversible or confirmable',
    description: 'For legal, financial, or data-modification submissions, submissions must be reversible, checked, or confirmed.',
    wcagReferences: [{ criterion: '3.3.4', name: 'Error Prevention (Legal, Financial, Data)', level: 'AA' }],
    severity: 'serious',
    remediation: 'Add confirmation dialogs, review steps, or undo mechanisms before final submission.',
    selectorHints: ['form[action]', 'button[type="submit"]', '[class*="checkout"]', '[class*="payment"]'],
    analysisMode: 'browser',
    checkFunction: 'Identify forms handling financial/legal data (payment fields, legal agreements). Check for confirmation steps, review pages, or undo mechanisms.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'help-available',
    category: 'input-assistance',
    title: 'Context-sensitive help should be available',
    description: 'Context-sensitive help should be available for form inputs and complex interactions.',
    wcagReferences: [{ criterion: '3.3.5', name: 'Help', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Provide help text, tooltips, or help links near form fields. Use aria-describedby for help text.',
    selectorHints: ['[aria-describedby]', '[class*="help"]', '[class*="hint"]'],
    analysisMode: 'static',
    checkFunction: 'Check form inputs for associated help text via aria-describedby, adjacent help icons/links, or placeholder text. Flag complex inputs without any help mechanism.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'aaa'],
  },
  {
    id: 'error-prevention-all',
    category: 'input-assistance',
    title: 'All form submissions should be reversible or confirmable',
    description: 'For all forms, submissions should be reversible, verified for errors, or confirmed by the user.',
    wcagReferences: [{ criterion: '3.3.6', name: 'Error Prevention (All)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Add confirmation steps or undo mechanisms for all form submissions.',
    selectorHints: ['form', 'button[type="submit"]'],
    analysisMode: 'browser',
    checkFunction: 'Check all forms for confirmation dialogs, review steps, or undo mechanisms before final submission.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'aaa', 'needs-browser'],
  },
  {
    id: 'redundant-entry',
    category: 'input-assistance',
    title: 'Redundant information entry must be auto-populated or selectable',
    description: 'Information previously entered by the user must be auto-populated or available for selection.',
    wcagReferences: [{ criterion: '3.3.7', name: 'Redundant Entry', level: 'A' }],
    severity: 'minor',
    remediation: 'Auto-fill previously entered information. Allow users to select from previous entries instead of retyping.',
    selectorHints: ['form', 'input[autocomplete]'],
    analysisMode: 'browser',
    checkFunction: 'In multi-step forms, detect fields requesting information already entered in previous steps. Verify auto-population or selection mechanism.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'needs-browser'],
  },
  {
    id: 'accessible-authentication-minimum',
    category: 'input-assistance',
    title: 'Authentication must not require cognitive function tests',
    description: 'Authentication should not require cognitive tests (puzzles, recall) unless alternatives exist.',
    wcagReferences: [{ criterion: '3.3.8', name: 'Accessible Authentication (Minimum)', level: 'AA' }],
    severity: 'serious',
    remediation: 'Support password managers (no paste blocking), passkeys, or OAuth. If CAPTCHA is used, provide accessible alternatives.',
    selectorHints: ['input[type="password"]', '[class*="captcha"]', '[class*="login"]', '[autocomplete="off"]'],
    analysisMode: 'browser',
    checkFunction: 'Check login forms for: paste blocked on password fields, CAPTCHAs without audio/alternative, cognitive tests. Verify autocomplete is not disabled on auth fields.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'needs-browser'],
  },
  {
    id: 'accessible-authentication-enhanced',
    category: 'input-assistance',
    title: 'Authentication must not require any cognitive tests',
    description: 'No step in authentication should rely on cognitive function tests, including object recognition.',
    wcagReferences: [{ criterion: '3.3.9', name: 'Accessible Authentication (Enhanced)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Eliminate all cognitive tests from authentication. Use passkeys, biometrics, or password managers exclusively.',
    selectorHints: ['[class*="captcha"]', '[class*="login"]'],
    analysisMode: 'browser',
    checkFunction: 'Same as accessible-authentication-minimum but stricter — flag any cognitive test in auth flow including image-based CAPTCHAs.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'aaa', 'needs-browser'],
  },
  {
    id: 'visible-labels',
    category: 'input-assistance',
    title: 'Form fields must have visible labels',
    description: 'Form fields must have persistent visible labels, not just placeholder text.',
    wcagReferences: [
      { criterion: '3.3.2', name: 'Labels or Instructions', level: 'A' },
      { criterion: '1.3.1', name: 'Info and Relationships', level: 'A' },
    ],
    severity: 'serious',
    remediation: 'Add visible <label> elements. Do not rely solely on placeholder as the label.',
    selectorHints: ['input[placeholder]', 'input:not([type="hidden"])'],
    analysisMode: 'static',
    checkFunction: 'Find inputs with placeholder but no visible associated <label> element. Flag placeholder-only labeling.',
    automationLevel: 'full',
    tags: ['automated', 'best-practice'],
  },
];
