/**
 * Keyboard accessibility rules — WCAG 2.1.x
 */
import { AccessibilityRule } from '../types.js';

export const keyboardRules: AccessibilityRule[] = [
  {
    id: 'keyboard-operable',
    category: 'keyboard',
    title: 'All functionality must be keyboard accessible',
    description: 'All interactive elements must be operable via keyboard (Tab, Enter, Space, Arrow keys).',
    wcagReferences: [{ criterion: '2.1.1', name: 'Keyboard', level: 'A' }],
    severity: 'critical',
    remediation: 'Use native interactive elements (<button>, <a>, <input>) or add tabindex="0" and keyboard event handlers.',
    selectorHints: ['[onclick]', '[role="button"]', '[role="link"]', '[role="tab"]'],
    analysisMode: 'browser',
    checkFunction: 'Find all interactive elements (clickable, role=button/link/tab/etc). Tab through the page and verify each is reachable. Test Enter/Space activates buttons, Enter activates links.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'keyboard-no-trap',
    category: 'keyboard',
    title: 'Keyboard focus must not be trapped',
    description: 'Users must be able to navigate away from any component using only the keyboard.',
    wcagReferences: [{ criterion: '2.1.2', name: 'No Keyboard Trap', level: 'A' }],
    severity: 'critical',
    remediation: 'Ensure all modal dialogs have Esc key support and visible close buttons. Avoid infinite tab loops.',
    selectorHints: ['[role="dialog"]', 'dialog', 'iframe', '[tabindex]'],
    analysisMode: 'browser',
    checkFunction: 'Tab through all focusable elements on the page. Detect if focus gets trapped in a loop (same sequence of elements repeating without user escape). Check modal dialogs allow Esc to close.',
    automationLevel: 'full',
    tags: ['automated', 'needs-browser'],
  },
  {
    id: 'keyboard-no-exception',
    category: 'keyboard',
    title: 'All functionality must be keyboard accessible (no exceptions)',
    description: 'All functionality must be available via keyboard without any exceptions.',
    wcagReferences: [{ criterion: '2.1.3', name: 'Keyboard (No Exception)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Ensure every interactive feature works with keyboard, including drag-and-drop, drawing, etc.',
    selectorHints: ['[draggable]', '[ondrag]'],
    analysisMode: 'browser',
    checkFunction: 'Same as keyboard-operable but flag ALL non-keyboard-operable elements regardless of exception claims.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser', 'aaa'],
  },
  {
    id: 'keyboard-character-shortcuts',
    category: 'keyboard',
    title: 'Single character key shortcuts must be remappable',
    description: 'If keyboard shortcuts use single character keys, users must be able to turn them off, remap, or they must only work on focus.',
    wcagReferences: [{ criterion: '2.1.4', name: 'Character Key Shortcuts', level: 'A' }],
    severity: 'minor',
    remediation: 'Allow users to disable or remap single-character shortcuts. Alternatively, make them active only when the component has focus.',
    selectorHints: ['[accesskey]'],
    analysisMode: 'browser',
    checkFunction: 'Detect accesskey attributes and JS keydown/keypress listeners for single character keys. Check if a mechanism exists to remap or disable them.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'wcag21', 'needs-browser'],
  },
  {
    id: 'keyboard-focusable-elements',
    category: 'keyboard',
    title: 'Interactive elements must be focusable',
    description: 'All interactive elements must be reachable via Tab key or included in the tab order.',
    wcagReferences: [{ criterion: '2.1.1', name: 'Keyboard', level: 'A' }],
    severity: 'critical',
    remediation: 'Use native focusable elements or add tabindex="0". Do not use tabindex > 0.',
    selectorHints: ['[onclick]', '[onmousedown]', '[role="button"]', '[role="link"]', 'div[tabindex]', 'span[tabindex]'],
    analysisMode: 'static',
    checkFunction: 'Find elements with click handlers or interactive ARIA roles. Verify they are natively focusable or have tabindex="0". Flag tabindex > 0 as anti-pattern.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'keyboard-positive-tabindex',
    category: 'keyboard',
    title: 'Positive tabindex values should not be used',
    description: 'tabindex values greater than 0 disrupt natural tab order and should be avoided.',
    wcagReferences: [{ criterion: '2.1.1', name: 'Keyboard', level: 'A' }],
    severity: 'minor',
    remediation: 'Use tabindex="0" or tabindex="-1" only. Restructure DOM order instead of using positive tabindex.',
    selectorHints: ['[tabindex]'],
    analysisMode: 'static',
    checkFunction: 'Query all elements with tabindex attribute. Flag any with tabindex > 0.',
    automationLevel: 'full',
    tags: ['automated', 'best-practice'],
  },
  {
    id: 'keyboard-scrollable-region',
    category: 'keyboard',
    title: 'Scrollable regions must be keyboard accessible',
    description: 'Scrollable content areas must be focusable so keyboard users can scroll them.',
    wcagReferences: [{ criterion: '2.1.1', name: 'Keyboard', level: 'A' }],
    severity: 'serious',
    remediation: 'Add tabindex="0" and role="region" with an accessible name to scrollable containers.',
    selectorHints: ['[style*="overflow"]'],
    analysisMode: 'browser',
    checkFunction: 'Find elements with overflow:scroll or overflow:auto where scrollHeight > clientHeight. Check if they are focusable (tabindex or native focusable).',
    automationLevel: 'full',
    tags: ['automated', 'needs-browser'],
  },
  {
    id: 'keyboard-event-handlers',
    category: 'keyboard',
    title: 'Mouse event handlers must have keyboard equivalents',
    description: 'Elements with mouse-specific handlers (mouseover, mousedown) must also have keyboard handlers.',
    wcagReferences: [{ criterion: '2.1.1', name: 'Keyboard', level: 'A' }],
    severity: 'serious',
    remediation: 'Add keyboard event handlers (onkeydown, onkeyup, onfocus, onblur) alongside mouse event handlers.',
    selectorHints: ['[onmouseover]', '[onmousedown]', '[onmouseup]', '[onmouseout]'],
    analysisMode: 'static',
    checkFunction: 'Find elements with mouse event attributes. Verify matching keyboard events exist: mouseover→focus, mouseout→blur, mousedown→keydown, click→keypress(Enter).',
    automationLevel: 'full',
    tags: ['automated'],
  },
];
