/**
 * Multimedia accessibility rules — WCAG 1.2.x Time-based Media
 */
import { AccessibilityRule } from '../types.js';

export const multimediaRules: AccessibilityRule[] = [
  {
    id: 'media-audio-transcript',
    category: 'multimedia',
    title: 'Audio-only content must have a transcript',
    description: 'Pre-recorded audio-only content must have a text transcript alternative.',
    wcagReferences: [{ criterion: '1.2.1', name: 'Audio-only and Video-only (Prerecorded)', level: 'A' }],
    severity: 'critical',
    remediation: 'Provide a text transcript that includes all spoken content and relevant sound descriptions.',
    selectorHints: ['audio', '[role="audio"]'],
    analysisMode: 'static',
    checkFunction: 'Find <audio> elements. Check for adjacent transcript link or aria-describedby pointing to transcript content.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'media-video-description',
    category: 'multimedia',
    title: 'Video-only content must have an alternative',
    description: 'Pre-recorded video-only content must have a text or audio alternative.',
    wcagReferences: [{ criterion: '1.2.1', name: 'Audio-only and Video-only (Prerecorded)', level: 'A' }],
    severity: 'critical',
    remediation: 'Provide a text description or audio track describing the visual content.',
    selectorHints: ['video'],
    analysisMode: 'static',
    checkFunction: 'Find <video> elements without audio tracks. Check for adjacent description link or aria-describedby.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'media-captions-prerecorded',
    category: 'multimedia',
    title: 'Pre-recorded video must have captions',
    description: 'All pre-recorded video with audio must have synchronized captions.',
    wcagReferences: [{ criterion: '1.2.2', name: 'Captions (Prerecorded)', level: 'A' }],
    severity: 'critical',
    remediation: 'Add a <track kind="captions"> element to the video, or use a captioning service.',
    selectorHints: ['video', 'track[kind="captions"]'],
    analysisMode: 'static',
    checkFunction: 'Find <video> elements. Check for <track kind="captions"> or <track kind="subtitles"> child. Also check for embedded captions in iframe players (YouTube, Vimeo).',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'media-audio-description-prerecorded',
    category: 'multimedia',
    title: 'Pre-recorded video must have audio description',
    description: 'Video content must have audio description for visual-only information.',
    wcagReferences: [
      { criterion: '1.2.3', name: 'Audio Description or Media Alternative (Prerecorded)', level: 'A' },
      { criterion: '1.2.5', name: 'Audio Description (Prerecorded)', level: 'AA' },
    ],
    severity: 'serious',
    remediation: 'Add an audio description track or provide a full text alternative for the video.',
    selectorHints: ['video', 'track[kind="descriptions"]'],
    analysisMode: 'static',
    checkFunction: 'Find <video> elements. Check for <track kind="descriptions"> or adjacent link to full text alternative.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'media-captions-live',
    category: 'multimedia',
    title: 'Live video must have captions',
    description: 'Live video content with audio must provide real-time captions.',
    wcagReferences: [{ criterion: '1.2.4', name: 'Captions (Live)', level: 'AA' }],
    severity: 'serious',
    remediation: 'Use a live captioning service (CART, AI-based) for live video streams.',
    selectorHints: ['video[data-live]', '[aria-live]'],
    analysisMode: 'manual',
    checkFunction: 'Detect live video streams. Flag for manual review — cannot fully automate live caption verification.',
    automationLevel: 'manual',
    tags: ['manual-review'],
  },
  {
    id: 'media-sign-language',
    category: 'multimedia',
    title: 'Pre-recorded video should have sign language interpretation',
    description: 'Sign language interpretation should be provided for all pre-recorded audio content in video.',
    wcagReferences: [{ criterion: '1.2.6', name: 'Sign Language (Prerecorded)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Provide a sign language video track or picture-in-picture sign language interpreter.',
    selectorHints: ['video'],
    analysisMode: 'manual',
    checkFunction: 'Flag all video elements for manual review of sign language availability.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'media-extended-audio-description',
    category: 'multimedia',
    title: 'Extended audio description for pre-recorded video',
    description: 'Where pauses in audio are insufficient, extended audio description should be provided.',
    wcagReferences: [{ criterion: '1.2.7', name: 'Extended Audio Description (Prerecorded)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Provide extended audio description that pauses the video when necessary.',
    selectorHints: ['video'],
    analysisMode: 'manual',
    checkFunction: 'Flag videos for manual review of extended audio description needs.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'media-full-text-alternative',
    category: 'multimedia',
    title: 'Synchronized media should have full text alternative',
    description: 'A full text alternative for all pre-recorded synchronized media should be available.',
    wcagReferences: [{ criterion: '1.2.8', name: 'Media Alternative (Prerecorded)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Provide a complete text document describing all audio and visual content of the media.',
    selectorHints: ['video', 'audio'],
    analysisMode: 'manual',
    checkFunction: 'Find media elements and check for adjacent full-text alternative links. Flag for manual quality review.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'media-live-audio-transcript',
    category: 'multimedia',
    title: 'Live audio-only must have text alternative',
    description: 'Live audio-only content must have a real-time text alternative.',
    wcagReferences: [{ criterion: '1.2.9', name: 'Audio-only (Live)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Provide live transcription or CART services for live audio content.',
    selectorHints: ['audio'],
    analysisMode: 'manual',
    checkFunction: 'Detect live audio streams. Flag for manual verification of live transcription availability.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'media-autoplay',
    category: 'multimedia',
    title: 'Media must not autoplay with sound',
    description: 'Audio or video that plays automatically for more than 3 seconds must have controls to pause/stop/mute.',
    wcagReferences: [{ criterion: '1.4.2', name: 'Audio Control', level: 'A' }],
    severity: 'serious',
    remediation: 'Remove autoplay or ensure audio is muted by default and user controls are available.',
    selectorHints: ['video[autoplay]', 'audio[autoplay]'],
    analysisMode: 'static',
    checkFunction: 'Find <video> and <audio> elements with autoplay attribute. Check if muted attribute is present. Verify pause/stop controls exist.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'media-video-accessible-controls',
    category: 'multimedia',
    title: 'Media players must have accessible controls',
    description: 'Custom media player controls must be keyboard accessible and properly labeled.',
    wcagReferences: [
      { criterion: '1.2.2', name: 'Captions (Prerecorded)', level: 'A' },
      { criterion: '2.1.1', name: 'Keyboard', level: 'A' },
    ],
    severity: 'serious',
    remediation: 'Ensure all media controls are focusable, have accessible names, and respond to keyboard input.',
    selectorHints: ['video', 'audio', '[role="slider"]'],
    analysisMode: 'browser',
    checkFunction: 'Find media elements and their associated controls. Test keyboard accessibility of play/pause/volume/seek. Verify ARIA labels on custom controls.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
];
