/**
 * Navigable rules — WCAG 2.4.x
 * Covers bypass blocks, page titles, focus order, link purpose, headings, focus visibility.
 */
import { AccessibilityRule } from '../types.js';

export const navigableRules: AccessibilityRule[] = [
  {
    id: 'bypass-blocks',
    category: 'navigable',
    title: 'Skip navigation link must exist',
    description: 'A mechanism must exist to skip repeated blocks of content (e.g., skip-to-main link).',
    wcagReferences: [{ criterion: '2.4.1', name: 'Bypass Blocks', level: 'A' }],
    severity: 'serious',
    remediation: 'Add a visible "Skip to main content" link as the first focusable element that jumps to <main>.',
    selectorHints: ['a[href="#main"]', 'a[href="#content"]', '[class*="skip"]'],
    analysisMode: 'static',
    checkFunction: 'Check for skip navigation links in the first few focusable elements. Verify the target ID exists and points to the main content area.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'page-titled',
    category: 'navigable',
    title: 'Page must have a descriptive title',
    description: 'Each page must have a <title> element that describes the page topic or purpose.',
    wcagReferences: [{ criterion: '2.4.2', name: 'Page Titled', level: 'A' }],
    severity: 'serious',
    remediation: 'Add a descriptive <title> that identifies the page content. Include site name for context.',
    selectorHints: ['title'],
    analysisMode: 'static',
    checkFunction: 'Check <head> for <title> element. Verify it is non-empty and not generic (e.g., "Untitled", "Page 1", "Home").',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'focus-order',
    category: 'navigable',
    title: 'Focus order must be logical and meaningful',
    description: 'The tab order of focusable elements must follow a logical reading sequence.',
    wcagReferences: [{ criterion: '2.4.3', name: 'Focus Order', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure DOM order matches visual layout. Remove positive tabindex values. Use CSS order carefully.',
    selectorHints: ['[tabindex]', 'a', 'button', 'input', 'select', 'textarea'],
    analysisMode: 'browser',
    checkFunction: 'Tab through all focusable elements. Record focus positions. Compare with visual layout order. Flag significant jumps in position (e.g., focus jumping from top-right to bottom-left).',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'link-purpose-in-context',
    category: 'navigable',
    title: 'Link purpose must be clear from context',
    description: 'The purpose of each link must be determinable from the link text or its programmatic context.',
    wcagReferences: [{ criterion: '2.4.4', name: 'Link Purpose (In Context)', level: 'A' }],
    severity: 'serious',
    remediation: 'Use descriptive link text. Avoid "click here" or "read more" alone. Use aria-label if visual text is insufficient.',
    selectorHints: ['a[href]', 'a'],
    analysisMode: 'static',
    checkFunction: 'Find all links. Check link text against generic terms (click here, read more, more, here, link). If generic, check for aria-label, aria-labelledby, or title. Check surrounding context (list item, paragraph, table cell).',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'multiple-ways',
    category: 'navigable',
    title: 'Multiple ways to find pages must be provided',
    description: 'More than one way must exist to locate a page (navigation, search, site map, links).',
    wcagReferences: [{ criterion: '2.4.5', name: 'Multiple Ways', level: 'AA' }],
    severity: 'minor',
    remediation: 'Provide at least two of: navigation menu, search, site map, table of contents, or cross-linking.',
    selectorHints: ['nav', '[role="navigation"]', '[role="search"]', 'input[type="search"]', '[class*="sitemap"]'],
    analysisMode: 'static',
    checkFunction: 'Check for presence of: navigation landmarks, search functionality, site map link, table of contents. Flag if fewer than 2 mechanisms found.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'headings-and-labels',
    category: 'navigable',
    title: 'Headings and labels must be descriptive',
    description: 'Headings and form labels must describe the topic or purpose of the content they introduce.',
    wcagReferences: [{ criterion: '2.4.6', name: 'Headings and Labels', level: 'AA' }],
    severity: 'minor',
    remediation: 'Use descriptive headings that convey the content topic. Ensure form labels clearly describe the expected input.',
    selectorHints: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'label'],
    analysisMode: 'static',
    checkFunction: 'Check headings and labels are non-empty. Flag very short headings (<3 chars) or generic labels. Use AI to assess descriptiveness.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'ai-assisted'],
  },
  {
    id: 'focus-visible',
    category: 'navigable',
    title: 'Focus indicator must be visible',
    description: 'All keyboard-focusable elements must have a visible focus indicator.',
    wcagReferences: [{ criterion: '2.4.7', name: 'Focus Visible', level: 'AA' }],
    severity: 'critical',
    remediation: 'Do not set outline:none without providing an alternative focus style. Use outline, box-shadow, or border for focus.',
    selectorHints: ['*:focus', '[style*="outline: none"]', '[style*="outline:none"]'],
    analysisMode: 'browser',
    checkFunction: 'Tab through focusable elements. For each, capture screenshot before and after focus. Compare pixels to detect visible change. Flag elements with no visible focus change.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'focus-visible-css',
    category: 'navigable',
    title: 'CSS must not suppress focus outlines without replacement',
    description: 'CSS rules that set outline:none or outline:0 on :focus must provide an alternative visible indicator.',
    wcagReferences: [{ criterion: '2.4.7', name: 'Focus Visible', level: 'AA' }],
    severity: 'serious',
    remediation: 'If using outline:none on :focus, add box-shadow, border, or background change as alternative.',
    selectorHints: ['*:focus'],
    analysisMode: 'browser',
    checkFunction: 'Parse stylesheets for rules targeting :focus with outline:none or outline:0. Check if those same rules include alternative indicators (box-shadow, border, background-color changes).',
    automationLevel: 'full',
    tags: ['automated', 'needs-browser'],
  },
  {
    id: 'location',
    category: 'navigable',
    title: 'User location within site should be indicated',
    description: 'Information about the user\'s location within a set of pages should be available (breadcrumbs, highlights).',
    wcagReferences: [{ criterion: '2.4.8', name: 'Location', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Add breadcrumb navigation, highlight current page in navigation, or use aria-current="page".',
    selectorHints: ['[aria-current]', 'nav', '[class*="breadcrumb"]'],
    analysisMode: 'static',
    checkFunction: 'Check for breadcrumb navigation (nav with aria-label="breadcrumb" or [class*="breadcrumb"]). Check for aria-current="page" on nav links.',
    automationLevel: 'full',
    tags: ['automated', 'aaa'],
  },
  {
    id: 'link-purpose-link-only',
    category: 'navigable',
    title: 'Link purpose must be clear from link text alone',
    description: 'The purpose of each link must be identifiable from the link text alone.',
    wcagReferences: [{ criterion: '2.4.9', name: 'Link Purpose (Link Only)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Make every link text self-descriptive. Avoid "click here", "more", "details" without context in the link text itself.',
    selectorHints: ['a[href]'],
    analysisMode: 'static',
    checkFunction: 'Check link text (including aria-label) against generic/ambiguous terms. Flag links that require surrounding context to understand purpose.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'aaa'],
  },
  {
    id: 'section-headings',
    category: 'navigable',
    title: 'Section headings should organize content',
    description: 'Headings should be used to organize content sections.',
    wcagReferences: [{ criterion: '2.4.10', name: 'Section Headings', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Add heading elements to identify each section of content.',
    selectorHints: ['h1', 'h2', 'h3', 'section', 'article'],
    analysisMode: 'static',
    checkFunction: 'Check <section> and <article> elements for heading children. Flag sections with large text blocks but no headings.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'aaa'],
  },
  {
    id: 'focus-not-obscured-minimum',
    category: 'navigable',
    title: 'Focused element must not be entirely hidden',
    description: 'When a UI component receives focus, it must not be entirely hidden by author-created content.',
    wcagReferences: [{ criterion: '2.4.11', name: 'Focus Not Obscured (Minimum)', level: 'AA' }],
    severity: 'serious',
    remediation: 'Ensure sticky headers/footers, banners, and overlays do not fully cover focused elements. Use scroll-padding.',
    selectorHints: ['[style*="position: fixed"]', '[style*="position: sticky"]'],
    analysisMode: 'browser',
    checkFunction: 'Tab through elements. For each focused element, check if any fixed/sticky elements overlap its bounding box entirely. Check scroll position accounts for sticky headers.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'needs-browser'],
  },
  {
    id: 'focus-not-obscured-enhanced',
    category: 'navigable',
    title: 'Focused element must not be partially hidden',
    description: 'When a UI component receives focus, no part of it should be hidden by author-created content.',
    wcagReferences: [{ criterion: '2.4.12', name: 'Focus Not Obscured (Enhanced)', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Ensure nothing overlaps any part of the focused element.',
    selectorHints: ['[style*="position: fixed"]', '[style*="position: sticky"]'],
    analysisMode: 'browser',
    checkFunction: 'Same as focus-not-obscured-minimum but flag even partial overlap of the focused element by fixed/sticky content.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'needs-browser', 'aaa'],
  },
  {
    id: 'focus-appearance',
    category: 'navigable',
    title: 'Focus indicator must meet size and contrast requirements',
    description: 'Focus indicators must have an area ≥ 2px perimeter around the component and 3:1 contrast between focused and unfocused states.',
    wcagReferences: [{ criterion: '2.4.13', name: 'Focus Appearance', level: 'AA' }],
    severity: 'serious',
    remediation: 'Use focus indicators with at least 2px outline that contrasts 3:1 against the unfocused state and adjacent colors.',
    selectorHints: ['*:focus', '*:focus-visible'],
    analysisMode: 'browser',
    checkFunction: 'Tab to each focusable element. Capture focused vs unfocused screenshots. Measure focus indicator area (must be ≥ 2px perimeter). Calculate contrast between focused and unfocused states.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'needs-browser'],
  },
];
