/**
 * Predictable behavior rules — WCAG 3.2.x
 */
import { AccessibilityRule } from '../types.js';

export const predictableRules: AccessibilityRule[] = [
  {
    id: 'on-focus-no-change',
    category: 'predictable',
    title: 'Focus must not cause unexpected context change',
    description: 'Receiving focus on any component must not trigger a change of context (page load, form submit, focus move).',
    wcagReferences: [{ criterion: '3.2.1', name: 'On Focus', level: 'A' }],
    severity: 'serious',
    remediation: 'Remove onfocus handlers that navigate, submit forms, or move focus. Use explicit user actions instead.',
    selectorHints: ['[onfocus]', 'select', 'input'],
    analysisMode: 'browser',
    checkFunction: 'Find elements with onfocus event handlers. Tab through the page and detect context changes (URL change, new window, form submission, focus forced elsewhere) triggered by focus alone.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'on-input-no-change',
    category: 'predictable',
    title: 'Input changes must not cause unexpected context change',
    description: 'Changing a form control value must not automatically trigger a context change without prior warning.',
    wcagReferences: [{ criterion: '3.2.2', name: 'On Input', level: 'A' }],
    severity: 'serious',
    remediation: 'Do not auto-submit forms on select change. Do not navigate on radio button selection. Add explicit submit buttons.',
    selectorHints: ['select[onchange]', 'input[onchange]', '[oninput]'],
    analysisMode: 'browser',
    checkFunction: 'Find select elements with onchange handlers. Detect if changing selection triggers navigation or form submission. Check for explicit submit mechanisms.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'consistent-navigation',
    category: 'predictable',
    title: 'Navigation must be consistent across pages',
    description: 'Navigation mechanisms repeated on multiple pages must occur in the same relative order.',
    wcagReferences: [{ criterion: '3.2.3', name: 'Consistent Navigation', level: 'AA' }],
    severity: 'minor',
    remediation: 'Keep navigation menus in the same order across all pages. Use templates for consistent layout.',
    selectorHints: ['nav', '[role="navigation"]'],
    analysisMode: 'browser',
    checkFunction: 'Compare navigation structure across multiple pages (requires multi-page scan). Extract nav link order and verify consistency.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'multi-page', 'needs-browser'],
  },
  {
    id: 'consistent-identification',
    category: 'predictable',
    title: 'Components with same function must be identified consistently',
    description: 'UI components with the same functionality must be labeled consistently across the site.',
    wcagReferences: [{ criterion: '3.2.4', name: 'Consistent Identification', level: 'AA' }],
    severity: 'minor',
    remediation: 'Use the same labels, icons, and alt text for recurring UI components (search, login, nav) across pages.',
    selectorHints: ['button', 'a', 'input[type="submit"]'],
    analysisMode: 'browser',
    checkFunction: 'Across multi-page scan, identify recurring components (search box, login, cart). Compare their labels for consistency.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'multi-page', 'needs-browser'],
  },
  {
    id: 'change-on-request',
    category: 'predictable',
    title: 'Context changes should only occur on user request',
    description: 'Context changes should be initiated only by user request, or a mechanism is available to turn off such changes.',
    wcagReferences: [{ criterion: '3.2.5', name: 'Change on Request', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Avoid automatic page redirects, pop-ups, or new windows without user action.',
    selectorHints: ['[target="_blank"]', 'meta[http-equiv="refresh"]'],
    analysisMode: 'both',
    checkFunction: 'Detect auto-redirects, auto-opening new windows, auto-playing content changes. Check meta refresh, JavaScript timers that change context.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'aaa'],
  },
  {
    id: 'consistent-help',
    category: 'predictable',
    title: 'Help mechanisms must be in consistent location',
    description: 'If help is provided on multiple pages, it must be in the same relative location on each page.',
    wcagReferences: [{ criterion: '3.2.6', name: 'Consistent Help', level: 'A' }],
    severity: 'minor',
    remediation: 'Place help links, chat widgets, or contact info in the same location on every page (e.g., footer, header).',
    selectorHints: ['[class*="help"]', '[class*="support"]', '[class*="chat"]', 'a[href*="help"]', 'a[href*="contact"]'],
    analysisMode: 'browser',
    checkFunction: 'Across multi-page scan, locate help mechanisms (help links, chat widgets, phone numbers). Compare their position relative to page structure for consistency.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'new-in-2.2', 'multi-page', 'needs-browser'],
  },
  {
    id: 'new-window-warning',
    category: 'predictable',
    title: 'Links opening new windows should warn users',
    description: 'Links with target="_blank" should indicate they open in a new window/tab.',
    wcagReferences: [{ criterion: '3.2.5', name: 'Change on Request', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Add visual indicator and aria text (e.g., "(opens in new tab)") to links with target="_blank".',
    selectorHints: ['a[target="_blank"]'],
    analysisMode: 'static',
    checkFunction: 'Find all links with target="_blank". Check for visual indicators (icon, text) and/or aria-label/sr-only text indicating new window behavior.',
    automationLevel: 'full',
    tags: ['automated', 'best-practice'],
  },
];
