/**
 * Readable content rules — WCAG 3.1.x
 */
import { AccessibilityRule } from '../types.js';

export const readableRules: AccessibilityRule[] = [
  {
    id: 'language-of-page',
    category: 'readable',
    title: 'Page must have a lang attribute',
    description: 'The <html> element must have a valid lang attribute identifying the primary language.',
    wcagReferences: [{ criterion: '3.1.1', name: 'Language of Page', level: 'A' }],
    severity: 'critical',
    remediation: 'Add lang attribute to the <html> element (e.g., lang="en", lang="he").',
    selectorHints: ['html'],
    analysisMode: 'static',
    checkFunction: 'Check <html> element for lang or xml:lang attribute. Verify the value is a valid BCP 47 language tag.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'language-of-parts',
    category: 'readable',
    title: 'Language changes must be identified',
    description: 'Content in a different language than the page default must have a lang attribute.',
    wcagReferences: [{ criterion: '3.1.2', name: 'Language of Parts', level: 'AA' }],
    severity: 'minor',
    remediation: 'Add lang attribute to elements containing text in a different language than the page default.',
    selectorHints: ['[lang]'],
    analysisMode: 'both',
    checkFunction: 'Use language detection on text nodes. Compare detected language with nearest ancestor lang attribute. Flag mismatches where no lang attribute overrides the page default.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'ai-assisted'],
  },
  {
    id: 'unusual-words',
    category: 'readable',
    title: 'Unusual words and jargon should be defined',
    description: 'A mechanism should exist to identify definitions for unusual words, idioms, and jargon.',
    wcagReferences: [{ criterion: '3.1.3', name: 'Unusual Words', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Provide a glossary, definition list (<dl>/<dfn>), or inline definitions for technical terms.',
    selectorHints: ['dfn', 'abbr', 'dl', '[class*="glossary"]'],
    analysisMode: 'static',
    checkFunction: 'Check for presence of glossary links, <dfn> elements, or <dl> definition lists. Flag pages with technical content but no definition mechanism.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'aaa'],
  },
  {
    id: 'abbreviations',
    category: 'readable',
    title: 'Abbreviations should have expanded form',
    description: 'A mechanism should exist to identify the expanded form of abbreviations.',
    wcagReferences: [{ criterion: '3.1.4', name: 'Abbreviations', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Use <abbr title="..."> for abbreviations, or provide expansion on first use.',
    selectorHints: ['abbr', 'acronym'],
    analysisMode: 'static',
    checkFunction: 'Find abbreviation-like text patterns (all-caps words ≥2 chars). Check if <abbr> with title is used. Flag abbreviations without expansion.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'aaa'],
  },
  {
    id: 'reading-level',
    category: 'readable',
    title: 'Content should be readable at lower secondary education level',
    description: 'Content should be written at a reading level no higher than lower secondary education, or a simplified version provided.',
    wcagReferences: [{ criterion: '3.1.5', name: 'Reading Level', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Simplify text or provide a simplified version. Use short sentences and common words.',
    selectorHints: ['p', 'article'],
    analysisMode: 'static',
    checkFunction: 'Calculate readability scores (Flesch-Kincaid, Gunning Fog) on page text content. Flag content above grade 9 reading level.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'ai-assisted', 'aaa'],
  },
  {
    id: 'pronunciation',
    category: 'readable',
    title: 'Pronunciation should be available for ambiguous words',
    description: 'A mechanism should exist to provide pronunciation for words where meaning is ambiguous without it.',
    wcagReferences: [{ criterion: '3.1.6', name: 'Pronunciation', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Provide pronunciation guides, ruby annotations, or links to audio pronunciation.',
    selectorHints: ['ruby', '[class*="pronunciation"]'],
    analysisMode: 'manual',
    checkFunction: 'Flag pages with homographs or technical terms for manual review of pronunciation guidance.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'valid-lang-attribute',
    category: 'readable',
    title: 'Lang attributes must have valid values',
    description: 'All lang attributes on the page must use valid BCP 47 language tags.',
    wcagReferences: [{ criterion: '3.1.1', name: 'Language of Page', level: 'A' }],
    severity: 'serious',
    remediation: 'Use valid BCP 47 language codes (e.g., "en", "en-US", "he", "ar").',
    selectorHints: ['[lang]'],
    analysisMode: 'static',
    checkFunction: 'Find all elements with lang attribute. Validate each value against BCP 47 standard (primary subtag: 2-3 letter ISO 639 code).',
    automationLevel: 'full',
    tags: ['automated'],
  },
];
