/**
 * Screen reader specific rules — NVDA, VoiceOver, JAWS patterns.
 * Live regions, announcements, reading order, landmark navigation.
 */
import { AccessibilityRule } from '../types.js';

export const screenReaderRules: AccessibilityRule[] = [
  {
    id: 'sr-page-landmarks',
    category: 'screen-reader',
    title: 'Page must have complete landmark structure',
    description: 'Page must have main, navigation, and complementary landmarks for screen reader navigation.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'serious',
    remediation: 'Use <main>, <nav>, <header>, <footer>, <aside> elements. Ensure all content is within landmarks.',
    selectorHints: ['main', 'nav', 'header', 'footer', 'aside', '[role="main"]', '[role="banner"]', '[role="contentinfo"]'],
    analysisMode: 'static',
    checkFunction: 'Verify page has: at least one <main> or role="main", navigation landmarks for menus, banner (header) and contentinfo (footer). Check all body content is inside a landmark.',
    automationLevel: 'full',
    tags: ['automated', 'nvda', 'voiceover'],
  },
  {
    id: 'sr-landmark-labels',
    category: 'screen-reader',
    title: 'Duplicate landmark roles must have unique labels',
    description: 'When multiple landmarks of the same type exist, each must have a unique accessible name.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'minor',
    remediation: 'Add aria-label or aria-labelledby to distinguish multiple nav, aside, or section landmarks.',
    selectorHints: ['nav', 'aside', 'section', '[role="navigation"]', '[role="complementary"]', '[role="region"]'],
    analysisMode: 'static',
    checkFunction: 'Group landmarks by role. For groups with 2+ elements, verify each has a unique aria-label or aria-labelledby.',
    automationLevel: 'full',
    tags: ['automated', 'nvda', 'voiceover'],
  },
  {
    id: 'sr-heading-structure',
    category: 'screen-reader',
    title: 'Heading structure must support screen reader navigation',
    description: 'Headings must form a navigable outline. Screen readers use headings as primary navigation.',
    wcagReferences: [
      { criterion: '1.3.1', name: 'Info and Relationships', level: 'A' },
      { criterion: '2.4.6', name: 'Headings and Labels', level: 'AA' },
    ],
    severity: 'serious',
    remediation: 'Ensure every major section has a heading. Use proper nesting (h1→h2→h3). Avoid empty headings.',
    selectorHints: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', '[role="heading"]'],
    analysisMode: 'static',
    checkFunction: 'Build heading tree from all h1-h6 and [role="heading"] elements. Check for: empty headings, skipped levels, no h1, sections without headings.',
    automationLevel: 'full',
    tags: ['automated', 'nvda', 'voiceover'],
  },
  {
    id: 'sr-live-region-updates',
    category: 'screen-reader',
    title: 'Dynamic content changes must announce via live regions',
    description: 'Content that updates dynamically must use ARIA live regions so screen readers announce changes.',
    wcagReferences: [{ criterion: '4.1.3', name: 'Status Messages', level: 'AA' }],
    severity: 'serious',
    remediation: 'Wrap dynamically updating content in aria-live="polite" (or "assertive" for urgent). Use role="status" or role="alert".',
    selectorHints: ['[aria-live]', '[role="status"]', '[role="alert"]', '[role="log"]', '[role="timer"]'],
    analysisMode: 'browser',
    checkFunction: 'Monitor DOM mutations. Identify content that changes dynamically (AJAX updates, notifications, counters). Verify changed content is within an aria-live region or has a live role.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'nvda', 'needs-browser'],
  },
  {
    id: 'sr-live-region-atomic',
    category: 'screen-reader',
    title: 'Live regions should use aria-atomic appropriately',
    description: 'aria-atomic="true" should be set when the entire live region should be re-announced on any change.',
    wcagReferences: [{ criterion: '4.1.3', name: 'Status Messages', level: 'AA' }],
    severity: 'minor',
    remediation: 'Set aria-atomic="true" on live regions where partial updates would be confusing. Use aria-atomic="false" for logs.',
    selectorHints: ['[aria-live]', '[aria-atomic]'],
    analysisMode: 'static',
    checkFunction: 'Find live regions. Check if aria-atomic is set appropriately: "true" for status messages, "false" or absent for chat logs and activity feeds.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'nvda'],
  },
  {
    id: 'sr-focus-management-spa',
    category: 'screen-reader',
    title: 'SPA route changes must manage focus',
    description: 'Single Page Application route changes must move focus to new content or announce the change.',
    wcagReferences: [
      { criterion: '4.1.3', name: 'Status Messages', level: 'AA' },
      { criterion: '2.4.3', name: 'Focus Order', level: 'A' },
    ],
    severity: 'serious',
    remediation: 'On SPA navigation, move focus to the main content heading or announce the new page via live region.',
    selectorHints: ['[role="main"]', 'h1', '[aria-live]'],
    analysisMode: 'browser',
    checkFunction: 'Trigger SPA navigation events. Monitor focus position after route change. Verify focus moves to main content or an announcement is made via live region.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser', 'spa'],
  },
  {
    id: 'sr-modal-focus-trap',
    category: 'screen-reader',
    title: 'Modals must trap focus and announce opening',
    description: 'When a modal opens, focus must move inside it, be trapped within it, and return to trigger on close.',
    wcagReferences: [
      { criterion: '2.4.3', name: 'Focus Order', level: 'A' },
      { criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' },
    ],
    severity: 'critical',
    remediation: 'Move focus to modal on open. Trap Tab/Shift+Tab within modal. Return focus to trigger on close. Use role="dialog" and aria-modal="true".',
    selectorHints: ['[role="dialog"]', '[aria-modal="true"]', 'dialog'],
    analysisMode: 'browser',
    checkFunction: 'Trigger modal opening. Verify: (1) focus moves inside modal, (2) Tab cycles only within modal, (3) Esc closes modal, (4) focus returns to triggering element.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'nvda', 'needs-browser'],
  },
  {
    id: 'sr-table-navigation',
    category: 'screen-reader',
    title: 'Tables must support screen reader table navigation',
    description: 'Data tables must use proper markup so screen readers can navigate by row/column.',
    wcagReferences: [{ criterion: '1.3.1', name: 'Info and Relationships', level: 'A' }],
    severity: 'serious',
    remediation: 'Use <table>, <thead>, <tbody>, <th scope="col/row">, <td>. Add <caption> for table purpose.',
    selectorHints: ['table', 'th', 'td', '[role="table"]', '[role="grid"]'],
    analysisMode: 'static',
    checkFunction: 'Find data tables. Verify: <th> with scope attributes, <caption> or aria-label, proper <thead>/<tbody> structure, no layout tables misidentified as data tables.',
    automationLevel: 'full',
    tags: ['automated', 'nvda', 'voiceover'],
  },
  {
    id: 'sr-image-announcements',
    category: 'screen-reader',
    title: 'Images must announce correctly in screen readers',
    description: 'Images must have alt text that reads well in screen readers. Decorative images must be silent.',
    wcagReferences: [{ criterion: '1.1.1', name: 'Non-text Content', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure alt text is concise and descriptive. Use alt="" for decorative images. Avoid redundant "image of" prefixes.',
    selectorHints: ['img', 'svg', '[role="img"]'],
    analysisMode: 'static',
    checkFunction: 'Check all images for: (1) alt text starting with "image of" or "picture of" (redundant), (2) alt text > 125 chars (too long), (3) decorative images with non-empty alt.',
    automationLevel: 'full',
    tags: ['automated', 'nvda', 'voiceover'],
  },
  {
    id: 'sr-link-context',
    category: 'screen-reader',
    title: 'Links must make sense when read out of context',
    description: 'Screen readers can list all links — each link text must be understandable independently.',
    wcagReferences: [{ criterion: '2.4.4', name: 'Link Purpose (In Context)', level: 'A' }],
    severity: 'minor',
    remediation: 'Use descriptive link text. Add aria-label for visual links with generic text. Use aria-describedby for additional context.',
    selectorHints: ['a[href]'],
    analysisMode: 'static',
    checkFunction: 'List all links with their accessible names. Flag duplicates with same text but different destinations. Flag generic text (More, Click here, Here, Read more).',
    automationLevel: 'partial',
    tags: ['semi-automated', 'nvda'],
  },
  {
    id: 'sr-form-announcements',
    category: 'screen-reader',
    title: 'Form fields must announce label, role, and state',
    description: 'Screen readers must announce the label, input type, required state, and error state of form fields.',
    wcagReferences: [
      { criterion: '4.1.2', name: 'Name, Role, Value', level: 'A' },
      { criterion: '3.3.2', name: 'Labels or Instructions', level: 'A' },
    ],
    severity: 'serious',
    remediation: 'Associate labels, set aria-required, aria-invalid, and aria-describedby for help/error text.',
    selectorHints: ['input', 'select', 'textarea', '[role="textbox"]', '[role="combobox"]'],
    analysisMode: 'browser',
    checkFunction: 'For each form control, compute the full screen reader announcement: accessible name + role + required state + description. Flag if any component is missing.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'nvda', 'needs-browser'],
  },
  {
    id: 'sr-skip-to-content',
    category: 'screen-reader',
    title: 'Skip link must be functional for screen readers',
    description: 'The skip navigation link must actually move screen reader focus to the main content.',
    wcagReferences: [{ criterion: '2.4.1', name: 'Bypass Blocks', level: 'A' }],
    severity: 'serious',
    remediation: 'Ensure skip link target has tabindex="-1" if not natively focusable, so focus actually moves.',
    selectorHints: ['a[href^="#"]', '#main-content', '#content', 'main'],
    analysisMode: 'browser',
    checkFunction: 'Find skip navigation links. Activate them. Verify focus actually moves to the target element (check document.activeElement matches the target).',
    automationLevel: 'full',
    tags: ['automated', 'nvda', 'needs-browser'],
  },
];
