/**
 * Timing rules — WCAG 2.2.x Enough Time
 */
import { AccessibilityRule } from '../types.js';

export const timingRules: AccessibilityRule[] = [
  {
    id: 'timing-adjustable',
    category: 'timing',
    title: 'Time limits must be adjustable',
    description: 'Users must be able to turn off, adjust, or extend any time limits set by the content.',
    wcagReferences: [{ criterion: '2.2.1', name: 'Timing Adjustable', level: 'A' }],
    severity: 'critical',
    remediation: 'Provide a way to turn off, adjust, or extend time limits. Warn before timeout with at least 20 seconds to extend.',
    selectorHints: ['meta[http-equiv="refresh"]', '[data-timeout]'],
    analysisMode: 'both',
    checkFunction: 'Check for meta refresh tags. Detect JavaScript setTimeout/setInterval that redirect or hide content. Verify timeout warnings and extension mechanisms exist.',
    automationLevel: 'partial',
    tags: ['semi-automated'],
  },
  {
    id: 'meta-refresh',
    category: 'timing',
    title: 'Meta refresh must not be used for timed redirects',
    description: 'Pages must not use <meta http-equiv="refresh"> with a time delay greater than 0.',
    wcagReferences: [{ criterion: '2.2.1', name: 'Timing Adjustable', level: 'A' }],
    severity: 'critical',
    remediation: 'Use server-side redirects (HTTP 301/302) instead of meta refresh. If used, set content="0".',
    selectorHints: ['meta[http-equiv="refresh"]'],
    analysisMode: 'static',
    checkFunction: 'Find <meta http-equiv="refresh"> elements. Flag any with content attribute value > 0.',
    automationLevel: 'full',
    tags: ['automated'],
  },
  {
    id: 'pause-stop-hide',
    category: 'timing',
    title: 'Moving content must have pause/stop/hide controls',
    description: 'Auto-updating, moving, blinking, or scrolling content that starts automatically must have controls.',
    wcagReferences: [{ criterion: '2.2.2', name: 'Pause, Stop, Hide', level: 'A' }],
    severity: 'serious',
    remediation: 'Provide pause, stop, or hide buttons for animated content. Ensure auto-updating information can be paused.',
    selectorHints: ['marquee', '[class*="carousel"]', '[class*="slider"]', '[class*="ticker"]', 'video[autoplay]'],
    analysisMode: 'browser',
    checkFunction: 'Detect animated elements: CSS animations, marquee, carousels, auto-scrolling. Check for visible pause/stop controls near the animated content.',
    automationLevel: 'partial',
    tags: ['semi-automated', 'needs-browser'],
  },
  {
    id: 'no-timing',
    category: 'timing',
    title: 'Timing should not be essential',
    description: 'Timing should not be an essential part of any event or activity, except for real-time events.',
    wcagReferences: [{ criterion: '2.2.3', name: 'No Timing', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Remove time limits from non-real-time interactions. Provide untimed alternatives.',
    selectorHints: ['[data-timeout]', '[data-countdown]'],
    analysisMode: 'manual',
    checkFunction: 'Flag pages with timer elements or countdown indicators for manual review.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'interruptions',
    category: 'timing',
    title: 'Interruptions should be postponable',
    description: 'Interruptions (alerts, updates) should be postponable or suppressible by the user.',
    wcagReferences: [{ criterion: '2.2.4', name: 'Interruptions', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Allow users to disable non-emergency interruptions. Provide notification preferences.',
    selectorHints: ['[role="alert"]', '[role="alertdialog"]', '[aria-live="assertive"]'],
    analysisMode: 'browser',
    checkFunction: 'Monitor for dynamic alerts and interruptions. Check if user preferences for notification suppression exist.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 're-authenticating',
    category: 'timing',
    title: 'Data must be preserved during re-authentication',
    description: 'If a session expires, data entered by the user must be preserved after re-authentication.',
    wcagReferences: [{ criterion: '2.2.5', name: 'Re-authenticating', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Save form data to session storage before timeout. Restore after re-authentication.',
    selectorHints: ['form'],
    analysisMode: 'manual',
    checkFunction: 'Flag forms on pages with session timeouts for manual verification of data preservation.',
    automationLevel: 'manual',
    tags: ['manual-review', 'aaa'],
  },
  {
    id: 'timeouts-warning',
    category: 'timing',
    title: 'Users must be warned of inactivity timeouts',
    description: 'Users must be informed about the duration of inactivity that will cause data loss.',
    wcagReferences: [{ criterion: '2.2.6', name: 'Timeouts', level: 'AAA' }],
    severity: 'minor',
    remediation: 'Warn users at the start of a process about any timeout. Preserve data for at least 20 hours of inactivity.',
    selectorHints: ['form', '[data-timeout]'],
    analysisMode: 'manual',
    checkFunction: 'Check for timeout warning messages at the beginning of multi-step processes. Flag forms without visible timeout information.',
    automationLevel: 'manual',
    tags: ['manual-review', 'wcag21', 'aaa'],
  },
];
