/**
 * Markdown report generator for A11Y test case suggestions.
 * Follows SuperchargeAI MD report style with emojis, tables, and clear sections.
 */

import type { TestCaseSuggestionResult, SuggestedTestCase, CategorySummary } from '../../types/suggestion-test-case.js';
import type { RuleCategory } from '../../rules/types.js';

const CATEGORY_EMOJI: Record<string, string> = {
  'images': '🖼️',
  'multimedia': '🎬',
  'adaptable': '📐',
  'distinguishable': '🎨',
  'keyboard': '⌨️',
  'timing': '⏱️',
  'seizures': '⚡',
  'navigable': '🧭',
  'input-modalities': '👆',
  'readable': '📖',
  'predictable': '🔄',
  'input-assistance': '💬',
  'compatible': '🔧',
  'aria': '🏷️',
  'forms': '📝',
  'screen-reader': '🔊',
};

function getPriorityEmoji(priority: string): string {
  return priority === 'high' ? '🔴' : priority === 'medium' ? '🟡' : '🟢';
}

function getCategoryEmoji(category: RuleCategory): string {
  return CATEGORY_EMOJI[category] ?? '📋';
}

export function generateSuggestionMdReport(result: TestCaseSuggestionResult): string {
  const lines: string[] = [];

  // Header
  lines.push('# ♿ A11Y Test Case Suggestions');
  lines.push('');
  lines.push(`## Target: ${result.pageTitle}`);
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| **URL** | ${result.url} |`);
  lines.push(`| **Scan Date** | ${result.scanDate} |`);
  lines.push(`| **Duration** | ${result.duration}s |`);
  lines.push('| **Scanner Version** | Smart A11y Scanner v0.1.0 |');
  lines.push('');
  lines.push('---');
  lines.push('');

  // Summary
  lines.push('## 📊 Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| **Total Suggestions** | ${result.totalSuggestions} |`);
  lines.push(`| **High Priority** | ${getPriorityEmoji('high')} ${result.prioritySummary.high} |`);
  lines.push(`| **Medium Priority** | ${getPriorityEmoji('medium')} ${result.prioritySummary.medium} |`);
  lines.push(`| **Low Priority** | ${getPriorityEmoji('low')} ${result.prioritySummary.low} |`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Detailed Test Cases by Category
  lines.push('## 🔍 Suggested Test Cases');
  lines.push('');

  // Group suggestions by category
  const byCategory = new Map<RuleCategory, SuggestedTestCase[]>();
  for (const suggestion of result.suggestions) {
    const existing = byCategory.get(suggestion.category) ?? [];
    existing.push(suggestion);
    byCategory.set(suggestion.category, existing);
  }

  // Render each category
  for (const [category, suggestions] of byCategory) {
    const emoji = getCategoryEmoji(category);
    const categoryName = category.charAt(0).toUpperCase() + category.slice(1);
    lines.push(`### ${emoji} ${categoryName} (${suggestions.length} suggestion${suggestions.length === 1 ? '' : 's'})`);
    lines.push('');

    // Sort by priority (high -> medium -> low)
    const priorityOrder = { high: 0, medium: 1, low: 2 };
    const sorted = suggestions.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]);

    for (const tc of sorted) {
      lines.push(`#### ${getPriorityEmoji(tc.priority)} TC-${tc.id}: ${tc.title}`);
      lines.push('');
      lines.push('| Field | Value |');
      lines.push('|-------|-------|');
      lines.push(`| **WCAG Criterion** | ${tc.wcagCriteria} — ${tc.wcagCriterionName} (Level ${tc.wcagLevel}) |`);
      lines.push(`| **Priority** | ${tc.priority.toUpperCase()} |`);
      lines.push(`| **Source** | ${tc.sourceType} |`);
      if (tc.element) {
        lines.push(`| **Element** | \`${tc.element}\` |`);
      }
      lines.push('');
      lines.push(`**Description:** ${tc.description}`);
      lines.push('');
      lines.push('**Test Steps:**');
      lines.push('');
      lines.push('| # | Action | Expected Result |');
      lines.push('|---|--------|-----------------|');
      tc.steps.forEach((step, idx) => {
        lines.push(`| ${idx + 1} | ${step.action} | ${step.expectedResult} |`);
      });
      lines.push('');
      lines.push(`**Rationale:** ${tc.rationale}`);
      lines.push('');
      if (tc.relatedRuleId) {
        lines.push(`*Related Rule: ${tc.relatedRuleId}*`);
        lines.push('');
      }
      lines.push('---');
      lines.push('');
    }
  }

  // Footer
  lines.push(`*Generated by Smart A11y Scanner v0.1.0 on ${result.scanDate}*`);
  lines.push('');

  return lines.join('\n');
}
